### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by varunpathania86** [GibbonEdu/core#1008]
Login using OAuth2 authentication

## Motivation
Most of the organizations nowadays use the applications which support OAuth2 authentication.
Providing OAuth2 authentication support in GibbonEdu will enable the schools to use existing login mechanism and SSO (single sign-on) feature.

## Example
https://github.com/thephpleague/oauth2-client

**Comment by SKuipers** [comment]
Hi @varunpathania86 

Thanks for your request. OAuth2 is also something that has been [discussed in our forums](https://ask.gibbonedu.org/search?Search=oauth) so I think there is definitely community support. I'm also a fan of PHP League libraries and their OAuth2 client would be an ideal solution. Is this something you'd be interested in working on developing? At the moment our efforts are focused on some ongoing refactoring, but we're happy to collaborate and offer some insights into how to go about integrating this with the core.

**Comment by SKuipers** [comment]
Hi @varunpathania86 

I've added OAuth2 support to our feature request board. https://github.com/GibbonEdu/core/projects/2

Thanks!
