### ISSUE TITLE
Homework submission time relays on server system timezone

### ISSUE THREAD

**Issue by vitovt** [GibbonEdu/core#1024]
**Describe the bug**
If servers timezone is different to Gibbon's settings timezone, submissed homework time is set to servers timezone.
But Presense timezone shows correct time.

**To Reproduce**

0. Set Gibbon's timezone different to web-server timezone
1. Go to 'Planner' as a student
2. Submit homework as a student
3. Go to planner as a teacher
4. Submitted homework time will be wrong (like on server timezone) (Number 2 on screenshot)
5. Submit Presense - time will be correct (Number 1 on screenshot)

**Expected behavior**
Homework time should be in the term of Gibbon time zone settings. The same like presense time.

**Screenshots**
![image](https://user-images.githubusercontent.com/315178/80321028-a5ca8500-8822-11ea-8a8f-2bfe324df64a.png)

**Your System**

 - Gibbon version v19.0.00] Vanilla
 - Browser chrome

**Comment by SKuipers** [comment]
Hi @vitovt 

I've checked out the code for homework submission but I wasn't able to reproduce this error. The homework timestamp is being set by a `date('Y-m-d H:i:s')` function, which appears to be correct. Looking at your screenshot, I see the times 00:51 and 00:49, which appear to be the same timezone, two minutes apart.

I wonder if what you may be seeing is session caching on the Gibbon timezone setting. If you changed this setting before submitting homework it may still be cached in the session for that user, and could appear to be incorrect. Generally the timezone setting doesn't change once the system is installed, so it is cached in the session for all users.

**Comment by vitovt** [comment]
Thankyou for your response.

>00:51 and 00:49, which appear to be the same timezone, two minutes apart.
Screenshot was taken after i've changed timezone on server. The difference before was several hours.

After changing sever timezone it start working OK without need to clear any cache and without relogin.

It is not critical for me, because in my school there is one timezone only and it is not hard to set correct on server. But maybe it will be confusing for large international school or with shared hosting.

**Comment by SKuipers** [comment]
Hi @vitovt 

Glad to hear you have it working on your server. 

I think it may be related to the time being encoded with `Y-m-d H:i:s`, which does not include timezone data, so it is always relative to the timezone of the server when the script is run. If the timezone is changed on the server, the time recorded in the database will still be the same as it was before.
