### ISSUE TITLE
Log In Screen

### ISSUE THREAD

**Issue by Ecogh** [GibbonEdu/core#1027]
it takes forever and log in screen never get to show up, pls assist

**Comment by rossdotparker** [comment]
Hi Ecogh, did you notice any slow performance during installation, or did that seem quicker than loading the login screen. When you expect to see the login screen, what are you seeing instead? Also, have you checked your PHP error logs to look for any errors? Thanks, Ross.

**Comment by SKuipers** [comment]
Hi @Ecogh

Hopefully you've found a solution to your issue. If not, be sure to post your issue to the [Gibbon support forums](ask.gibbonedu.org/). We are directing support requests to the forums as this helps us create a public knowledge base that other users can search if they have the same issue.

Thanks!
