### ISSUE TITLE
Reports Unexpected Behavior for Internal Assessment

### ISSUE THREAD

**Issue by ghulamabbas93** [GibbonEdu/core#1037]
**Describe the bug**

When we add internal assessment in template of Reports. and Then we enter data for internal assessment for a subject in internal assessment and enter attainment and comment.

After this when we generate report it duplicates over the subject again and again reaching up to 10 pages. 
**To Reproduce**

1. Go to 'Reports'
2. Click on 'Templates'
3. Scroll down to 'Internal Assessment'
4. See error in Generating Reports

**Expected behavior**

It should only write once not again and again same information.
**Screenshots**

![image](https://user-images.githubusercontent.com/53601279/81221112-d3ba8100-8ffb-11ea-8d16-aa48eab2303c.png)

**Your System**

 - Gibbon version  v19.0.00
 - Browser chrome

**Additional context**

**Comment by SKuipers** [comment]
Hi Ghulam,

Well caught! It was indeed a bug. I've pushed a fix which you can find here: https://github.com/GibbonEdu/core/commit/01fd82edbd327e1982da81d6a0d07c9fd3dc3f2b

Thanks! 😃
