### ISSUE TITLE
Raspberry pi4 Apache2 Phpmyadmin and virtual host with the Gibbon files in it

### ISSUE THREAD

**Issue by GarethHards** [GibbonEdu/core#1051]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your System**
pi4 php7.3 apache2 phpmyadmin ubuntu 19.04
 - Gibbon version [e.g. v19
 - Browser [e.g. chromium

**Additional context**
 My virtual server test html page worked perfectly and when i removed the file and replaced it with the Gibbon unzipped files and folders and used my browzer to the virtual host i get an error and a saying unable to handle the request

**Comment by rossdotparker** [comment]
Hi Gareth, thanks for trying Gibbon, and welcome to the community. Is it possible for you to check your PHP error logs, as this normally gives a clear indication of where the issue lies. In Ubuntu  the location of the logs is /var/logs/apache2/error. Thanks!

**Comment by jimbo8098** [comment]
I suspect Ross' suggestion will be helpful but this sounds like a file ownership issue to my. If it's helpful, here's an installation guide I wrote for an Ubuntu offshoot.

https://docs.gibbonedu.org/administrators/getting-started/installing-gibbon/install-ubuntu-debian/
