### ISSUE TITLE
Extending Gibbon to College Management System

### ISSUE THREAD

**Issue by jowinjohnchemban** [GibbonEdu/core#1086]
**Is your development discussion related to a problem?**

Yes

**Describe the solution you're proposing**

Can Please develop this great idea to college management system.

**Describe alternatives you've considered**

[Linways AMS](https://linways.com/features)

**Additional context**

[ask.gibbonedu.org](https://ask.gibbonedu.org/discussion/2983/extending-gibbon-to-college-management-system#latest)

**Comment by SKuipers** [comment]
This question has [been responded to](https://ask.gibbonedu.org/discussion/2983/extending-gibbon-to-college-management-system#latest) on the forums so I am closing it here. Thanks!
