### ISSUE TITLE
FastFinder search not working

### ISSUE THREAD

**Issue by varunpathania86** [GibbonEdu/core#1091]
**Describe the bug**
Fast finder searching functionality not working.

**To Reproduce**
1. Go to 'Fast finder search box'
2. Type any keyword
3. Notice the search autocomplete list.
4. There is only "Searching..." text showing up.

**Expected behavior**
The autocomplete or drill-down list of the fast finder must show the search results based on the keywords entered.

**Screenshots**
![FastFinderIssue](https://user-images.githubusercontent.com/1655067/91354662-b0198180-e80a-11ea-9375-62ce73381932.png)
**Your System**
 - Gibbon version v20.0.00
 - Browser chrome, edge
 - PHP 7.4.3
 - MySql 8.0.21-0ubuntu0.20.04.4

**Additional context**
On typing keyword "Act" the following ajax request is made:
 - /index_fastFinder_ajax.php?callback=jQuery224027764501235700845_1598474170830&q=Act&_=1598474170831
 - The ajax response contains the search data but not shown up on UI.
 - In the previous versions the **callback** query-string parameter was not there.

**Comment by rossdotparker** [comment]
This is often a sign that your session has timed out, and you've been logged out. Can you click on Home int he main menu, and see if you stay logged in, or end up logged out? We can definitely make Gibbon handle this more gracefully!

**Comment by varunpathania86** [comment]
> This is often a sign that your session has timed out, and you've been logged out. Can you click on Home int he main menu, and see if you stay logged in, or end up logged out? We can definitely make Gibbon handle this more gracefully!

I initially thought the same. But the ajax request is responding with correct data.

![image](https://user-images.githubusercontent.com/1655067/91604232-ee8a7a00-e98b-11ea-8395-dea3ebbb4502.png)


Following are the HTTP response headers:

![image](https://user-images.githubusercontent.com/1655067/91604476-5771f200-e98c-11ea-9c57-474ed72ae6aa.png)


And the HTTP request headers:

![image](https://user-images.githubusercontent.com/1655067/91604586-956f1600-e98c-11ea-8202-b3cacd9eb1bf.png)


**Not sure why the query parameters are there (other than "q")**
This is my test server and I have installed multiple Gibbon applications (v20.0.00).
Only new installations (_following the same steps_) are having this issue.

**Comment by SKuipers** [comment]
Hi @varunpathania86

I notice in your initial email you're using MySQL 8, which we've discovered is not necessarily compatible with Gibbon v20. We've made changes to the v21 development environment to make it compatible. If this install is running on your test server, would you be interested in testing the current v21 branch of Gibbon and seeing if this solves your issue?

https://github.com/GibbonEdu/core/tree/v21.0.00

Thanks!
Sandra

**Comment by varunpathania86** [comment]
Hi @SKuipers 

I also tried v21 but the issue is still there (But thanks for the nice and decent UI).
However, on the same test machine, another instance of Gibbon with the same v20 version is working fine.

I noticed that after I updated my OS using `apt-get upgrade` command, only new Gibbon installations (v20 or v21) giving this error but the previously installed instances (v20 or v21) are working fine.

**Comment by SKuipers** [comment]
Hi @varunpathania86. We haven't had any luck replicating this error, v21 and MySQL 8 seem to be running fine on the systems we have in development and production. I wonder if your fresh server installs may be missing one of the PHP extensions, such as gettext or mbstring, sometimes these are not enabled by default.

**Comment by SKuipers** [comment]
This issue has been inactive so I'm closing it for now, feel free to comment if you have more info and we'll re-open it. Thanks!
