### ISSUE TITLE
Facility (Space): Database Form Factory; createSelectSpace does not allow for sorting by type

### ISSUE THREAD

**Issue by powertashton** [GibbonEdu/core#1108]
**Is your development discussion related to a problem?**
I use the "type" column of gibbonSpace to define the building that a location is within, as we have a lot of different facilities and it is easiest to sort each location, by their parent location. However selects that use the database form factory's ->addSelectSpace do not allow for any organisation beyond just listing all the locations out, which could be quite frustrating.

**Describe the solution you're proposing**
```php 
$facilityGateway = $container->get(FacilityGateway::class);
    $criteria = $subcategoryGateway->newQueryCriteria(true)
            ->sortBy(['type', 'name'])
            ->fromPOST();
    $facilityData = $facilityGateway->queryFacilities($criteria);
    
     $row = $form->addRow();
        $row->addLabel('gibbonSpaceID', __('Facility'));
        $row->addSelect('gibbonSpaceID')
            ->fromDataSet($facilityData, 'gibbonSpaceID', 'name', 'type')
            ->placeholder()
            ->isRequired();
```
This is the current workaround I've used (In the v1.3 version of the HelpDesk Module), which uses a regular select instead, but I know (for example) addSelectStudent does allow for the same sort of sorting from the form factory.

**Describe alternatives you've considered**
I've also considered instead of using grouped sorts, the addSelectSpace could be two selects chained together, however the implementation of this may require additional work.

**Additional context**
Without sorting
![image](https://user-images.githubusercontent.com/48048360/93010439-1f3ef600-f5bf-11ea-9d1a-5e0492f43e90.png)
With sorting
![image](https://user-images.githubusercontent.com/48048360/93010617-0d5e5280-f5c1-11ea-8ca2-937bde5c4626.png)

**Comment by SKuipers** [comment]
Hi Ash! Sounds like a great feature to add. I think we could update the createSelectSpace method in the DatabaseFormFactory to add groupings by default, they're likely to be useful for pretty much any school. Feel free to PR this change : )
