### ISSUE TITLE
School Admin: Undefined Variable when creating department

### ISSUE THREAD

**Issue by powertashton** [GibbonEdu/core#1109]
**Describe the bug**
Notice: Undefined variable: AI in /Applications/MAMP/htdocs/helpdesk/tests/modules/School Admin/department_manage_addProcess.php on line 62

**To Reproduce**
1. Go to Departments Manage in School Admin
2. Click on Add (to add a department
3. Fill out form

**Expected behavior**
For a department to be created without an error

**Screenshots**

![image](https://user-images.githubusercontent.com/48048360/93034182-c8dbc100-f66b-11ea-9b8e-8fcb5c1cbe53.png)

**Your System**

 - Gibbon version v21
 - Browser - Microsoft Edge (Mac OS, Chromium version) and Firefox
 - PHP Version v7.1.0
 - MySQL 5.6.34
 - Locally hosted on MAMP

**Additional context**
 - Problem initially detected using the acceptance tests, and then tested manually to find the same issue
![image](https://user-images.githubusercontent.com/48048360/93034285-27a13a80-f66c-11ea-8153-98a89418efea.png)

**Comment by powertashton** [comment]
Fixed on PR: #1110

**Comment by SKuipers** [comment]
Thanks! Looks like in many systems the notice wasn't breaking the addProcess so this one slipped by. Well caught 👍
