### ISSUE TITLE
System Default Language and Personal Language not working.

### ISSUE THREAD

**Issue by nobicycle** [GibbonEdu/core#12]
Gibbon Version 9.
Example: id_ID

echo "select code,systemDefault from gibboni18n;"|mysql -u root -p
gibbon Enter password: 
code	systemDefault
en_GB	N
en_US	N
es_ES	N
zh_CN	N
zh_HK	N
pl_PL	N
it_IT	N
id_ID	Y
ar_SA	N
fr_FR	N

$ ls -l /srv/http/gibbon/i18n/id_ID/LC_MESSAGES/
total 2456
-rwxrwxrwx 1 http http   49115 04.02.2015 08:27 gibbon.mo*
-rwxrwxrwx 1 http http 2463812 04.02.2015 08:27 gibbon.po*

If I logout and login I see no effect on menus and submenus.
I also tried with Spanish, but it did not seem to work either.

Ross, Thanks for the app.

**Comment by rossdotparker** [comment]
nobicycle, sorry to hear about this issue. Are you by any chance using nginx as your web server? As long as you have gettext installed and activated in PHP there should be no issues getting it running in Apache. However, nginx has eluded us this far. Can you check your server logs to see if there are any issues related to gettext?

**Comment by nobicycle** [comment]
Hi Ross,
Not nginx . It's apache.
I did notice a calendar popup appeared in Spanish, but the menus, etc
remained in English.
There were quite a few errors, but nothing to do with gettext.
Let me clean it up and try again.
Re coding fingerprints, the Open Source app that does attendance (1:n =
identification)  I referenced is 95% complete. It is written in Python.
It saves to sqlite3 but that could easily become another DB. Python is
cross-platform of course.
How would you envisage interfacing it? IMO it is better to keep it in
sqlite3 and upload at intervals whenever networking is up, because
networking may be down or unavailable, for example during field trips
or activities outside of school. I have implemented that as a systemd
service on Linux. For Windows and Mac it should be easy too.

However, I think you should test the hardware for reliability of scan
before considering further, to make sure it fits in at your
establishment. Some may object to "treating students as criminals" :-)
This one is well supported on all OS. It is the size of a cigarette
packet.
http://www.aliexpress.com/item/Free-Shipping-Digital-Persona-Fingerprint-Reader-USB-Biometric-Fingerprint-Scanner-Sensor-reader-URU4000B-wholesale-dropshipping/2024269617.html

**Comment by nobicycle** [comment]
Hi Ross,

I cleared the apache error log, restarted, used Gibbon and then
rechecked the log. No errors were in the log. 

I switched system default language to Indonesian and Spanish,
http://localhost/gibbon/index.php?q=/modules/System%20Admin/i18n_manage.php

logging in and out each time. 
No effect - that is, everything visible was in English.

phpinfo.pdf attached.

Regards

**Comment by rossdotparker** [comment]
Nobicycle, that is interesting. Do you definitely have the locales installed on the machine? Take a look at https://help.ubuntu.com/community/Locale for how to do this on Ubuntu (other distros should be similar).

In terms of the fingerprint scanning, it would not go down well at my school, so I will not look into it further. I really appreciate the idea, just need to focus on other things. Thanks!

**Comment by myii** [comment]
@nobicycle This might be a bit late but I was having the same problem, running on Ubuntu 14.04, trying to get Arabic working.

Before fixing:
```
$ locale -a
...
ar_QA.utf8
ar_SA.utf8
...
```

Checked in the database for the user's language preference:
```
'0011', 'ar_SA', 'العربية - المملكة العربية السعودية', 'Y', 'N', 'Abdul Rahman Yousef', '', 'dd/mm/yyyy', '/^(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\\d\\d$/i', 'd/m/Y', 'Y'
```

So generated the specific locale and restarted Apache:
```
$ sudo locale-gen ar_SA
$ sudo service apache2 restart
```

After fixing:
```
$ locale -a
...
ar_QA.utf8
ar_SA
ar_SA.iso88596
ar_SA.utf8
...
```

And this worked for me.

@rossdotparker BTW, while I was hunting around for answers, got an SSL error trying to connect to https://www.gibbonedu.org/support/administrators/multilingual-internationalisation-localisation/:

> An error occurred during a connection to www.gibbonedu.org. Peer reports it experienced an internal error. (Error code: ssl_error_internal_error_alert)
