### ISSUE TITLE
Make Gibbon PHP 8 ready

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#1210]
**Is your development discussion related to a problem?**

PHP 8.0 is out. It's time to make Gibbon forward-compatible with PHP 8.x.

**Describe the solution you're proposing**
1. Add PHP 8 as a test target.
2. Handle whatever error we encounter.
3. Hopefully we can get both PHP 7.x and PHP 8.x happy.

**Describe alternatives you've considered**
I don't see any.

**Additional context**
Already encountered some compatibility issues in `Gibbon\Contract\Database\Connection` and `Gibbon\Contract\Database\Result` that would break the installer. Haven't started looking into the modules yet. Hopefully not much needs to be changed.

**Comment by SKuipers** [comment]
Hi Koala, thanks for getting the ball rolling. Yep, PHP 8 compatibility is a good goal for v22. Lets keep this discussion open and use it to track our progress in this area 👍

**Comment by SKuipers** [comment]
I've pushed an initial fix for the database issues, which means that pages will now load and the installer will run, albeit with some deprecation messages related to Twig. https://github.com/GibbonEdu/core/commit/805b0af191a3abe4b0ae279f5299f99b12146951 

I'll work on a few more compatibility issues today, but I suspect the majority of them will be uncovered through testing and general use.

**Comment by abdirooble** [comment]
<----I'm posting this for the second time, hoping to get faster answer ;).----/>

hey guys!
I have two questions.
can someone tell me which stacks Gibbon has?
and do you use a framework for PHP (laravel) or only PHP?

**Comment by yookoala** [comment]
> <----I'm posting this for the second time, hoping to get faster answer ;).----/>
> 
> hey guys!
> I have two questions.
> can someone tell me which stacks Gibbon has?
> and do you use a framework for PHP (laravel) or only PHP?

OT. Please see my reply in your other comment.

**Comment by rossdotparker** [comment]
Hi abdirooble, whilst I definitely appreciate your enthusiasm, multiple posts and emails acts to slow us all down. We work across multiple time zones, offering volunteer support to help as many people as we can. Resources are limited. If you make a single post ([to the forums](https://ask.gibbonedu.org/) as Koala pointed out in his other reply), we'll get back to you there as soon as we can. Cheers : ) Ross

**Comment by SKuipers** [comment]
Hi Koala, with the changes we've made earlier in the year, and the tests running on PHP 8, it's looking like we've caught all the known issues with this version. I'm going to mark this issue as resolved, in preparation for the v22 release, but we'll be sure to add PHP 8 as one of the versions we test in the upcoming full system test. Thanks again for your work setting this up! 👍
