### ISSUE TITLE
Migration to Travis-ci.com?

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#1225]
**Is your development discussion related to a problem?**
[travis-ci.org](https://travis-ci.org) is getting slower and slower. Sometime it takes hours for the test to start after triggered. Given that it is [scheduled to shutdown](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom), it's understandable that it is not given the same resource as [travis-ci.com](https://travis-ci.com), which all .org repositories will eventually migrated to.

**Describe the solution you're proposing**
Other developers reported that their CI Test / Build are more responsive at travis-ci.com (i.e. faster to start after triggered). I believe we should manually migrate there. You can follow the steps here to migrate:

* https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository

**Describe alternatives you've considered**

Alternatively, we can simply drop Travis CI all together. We already have GitHub Actions setup for CI test. Redundancy is a nice-to-have. Not a must.

Another alternative would be to wait for the automatic process. The transition should be in "several weeks" anyway. But the tests would still be slow at the moment.

**Additional context**

* [StackExchange: What is the Difference between Travis-ci.org and Travis-ci.com](https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com)

* Notice on the top of the [travis-ci.org page](https://travis-ci.org/github/GibbonEdu/core)
  ![2021-01-27 12-23-11 的螢幕擷圖](https://user-images.githubusercontent.com/91274/105942583-76d78d00-609a-11eb-8d88-4bf750cb3bcc.png)

* Current status of [travis-ci.com page](https://travis-ci.com/github/GibbonEdu/core)
  ![2021-01-27 12-28-46 的螢幕擷圖](https://user-images.githubusercontent.com/91274/105942975-417f6f00-609b-11eb-8367-8782446b2529.png)

**Comment by SKuipers** [comment]
Thanks Koala. Now that the GitHub actions are streamlined and working well, I'm tempted to drop the Travis CI check. This would speed up the tests, and prevent us from having to manage the configuration of two different CI systems.

**Comment by yookoala** [comment]
That's OK for me 🙂

**Comment by SKuipers** [comment]
Okay, I've removed the commit hook, so it's no longer in the tests list. It looks like if we did migrate, we'd get a limited number of 'build credits', and would have to apply to have the repo recognized for their free open source plan. At least on GitHub, its already free and already setup and running well (thanks again!)
