### ISSUE TITLE
phpleague ReflectionContainer uses deprecated ReflectionParameter::getClass

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#1226]
**Describe the bug**
The ArgumentResolverTrait in phpleague 2.4.1 still uses the deprecated ReflectionParameter::getClass method. This issue is fixed in [eb23e27](https://github.com/thephpleague/container/commit/75f01de3d99d8a36bd5a5567090540efe245bcb6#diff-c8fbc16c578d79040b51d66616a591a41fa8993f58ff07217c3e82a4827a4957), which got merged into [v3.3.3](https://github.com/thephpleague/container/releases/tag/3.3.3).

As for the 2.x branch, the last update was 2016. And the getClass call is still there:
https://github.com/thephpleague/container/blob/7b57d9455cac5fd1107ba1836a293cda64371fa3/src/Argument/ArgumentResolverTrait.php#L54

The most obvious way to fix this is to upgrade the "phpleague/container" package. It's 3.x branch claims to support PHP 7.0 - PHP 8.0 (experimental) while its 2.x branch supports PHP up to 7.1 only. One difference between this and #1214 is that it is not a development dependency. Changing the container library would change a bunch of files in /vendor unless either #1123 or #1209 is merged first.

**To Reproduce**
1. Checkout GibbonEdu latest source commit (e.g. 18d25c8)
2. Using the source folder as docroot, start a PHP 8 test server with `display_error=1` and `error_reporting=E_ALL` (i.e. showing deprecated warnings). For example with this command:
    ```
    php --server 127.0.0.1:8888 \
            --docroot . \
            --define display_startup_errors=1 \
            --define display_errors=1 \
            --define error_reporting=E_ALL
    ```
3. Visit the site with browser. The message should be easily seen.

**Expected behavior**
Do not see this kind of message at all.

**Screenshots**
![2021-02-02 12-41-45 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106553300-1772f480-6554-11eb-8098-5d4e48df6fe3.png)
![2021-01-27 23-45-40 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106017991-09f4df00-60fc-11eb-953e-615de03e681f.png)
![2021-01-28 00-02-05 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106018047-1aa55500-60fc-11eb-8b07-1ac9714f8432.png)

**Your System**
 - Gibbon version: v22.0.00 latest
 - Browser: PhpBrowser of Codeception

**Comment by abdirooble** [comment]
hey guys! 
I have two questions.
can someone tell me which stacks Gibbon has?
and do you use a framework for PHP (laravel) or only PHP?

**Comment by yookoala** [comment]
> hey guys! 
> I have two questions.
> can someone tell me which stacks Gibbon has?
> and do you use a framework for PHP (laravel) or only PHP?

The question is not related to this issue.

For general enquiries and support, please use the forum site:
https://ask.gibbonedu.org/

P.S. No. Gibbon is not using any framework.
