### ISSUE TITLE
Occasional fail in activity enrollment test, with MariaDB

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#1237]
**Describe the bug**
Working on the GitLab CI, I saw occasional failure in the `ManageActivitiesCept`.

```
1) ManageActivitiesCept: Add, edit and delete an activity as an admin and test the enrollment and view of a student
 Test  acceptance/Activities/ManageActivitiesCept.php
 Step  See "Activity Enrolment",".trailEnd"
 Fail  Element located either by name, CSS or XPath element with '.trailEnd' was not found.
Scenario Steps:
 19. $I->see("Activity Enrolment",".trailEnd") at config/support/AcceptanceTester.php:74
 18. $I->click("Enrolment","//td[contains(text(),'T2 Te...") at acceptance/Activities/ManageActivitiesCept.php:26
 17. $I->amOnPage("/index.php?q=/modules/Activities/act...") at config/support/AcceptanceTester.php:127
 16. $I->see("Your request was completed suc...",".success") at config/support/AcceptanceTester.php:79
 15. $I->click("Submit") at acceptance/Activities/ManageActivitiesCept.php:21
 14. $I->fillField("name","T2 Test Activity") at acceptance/Activities/ManageActivitiesCept.php:20
```

![2021-01-29 18-23-31 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106263280-22c9d580-625f-11eb-9fb2-aea0d0a7d32e.png)

This bug is strange:
* This only occasionally happen. And if I rerun the tests, the test would usually pass on the 2nd run.
* The issue is NOT relevant to the PHP version.
* It always fail at the same step: after test clicking on the "Enrolment" link in the activities listing table of the "Manage Activities" page.
* The recovered fail HTML page (supposed be displaying at the point of fail) is always showing "You do not have access to this action." (Hence cannot see the breadcrumb at all)
  ![2021-01-29 15-47-37 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106263650-a1267780-625f-11eb-89d1-00344fe3c4f3.png)
* There are 2 lines of code that would trigger that message. The first one is an `isActionAccessible()` call, which is not the issue. The second one is this query
  ```mysql
  SELECT
    gibbonActivity.*,
    NULL as status,
    gibbonActivityStaff.role
  FROM
    gibbonActivity
    JOIN gibbonActivityStaff ON (gibbonActivity.gibbonActivityID=gibbonActivityStaff.gibbonActivityID)
  WHERE
    gibbonActivity.gibbonActivityID=:gibbonActivityID AND
    gibbonActivityStaff.gibbonPersonID=:gibbonPersonID AND
    gibbonActivityStaff.role='Organiser' AND
    gibbonSchoolYearID=:gibbonSchoolYearID AND
    active='Y'
  ORDER BY name
  ```
  In the last failure, the relevant values of the placeholders:
  ```php
  [
    'gibbonPersonID' => '0000002773',
    'gibbonSchoolYearID' => '025',
    'gibbonActivityID' => '00002336',
  ]
  ```
  which returns 0 results. Hence the access denied message.
* After recovering the SQL dump, I found no `gibbonActivityStaff` record that has the relevant `gibbonActivityID`:
  ```sql
  SELECT * FROM gibbonActivityStaff WHERE gibbonActivityID='00002336';
  ```
  ```
  Empty set (0.001 sec)
  ```

This is not really a CI bug. It indicates that some times the behavior of the system acts differently. And there could be a real bug causing the issue.

**To Reproduce**
1. Push anything to the GitHub v22.0.00 branch
2. Check on the pipeline page [here](https://gitlab.com/yookoala/gibboneducore/-/pipelines)
3. Wait.
4. When there is a failed job, open it and download the Job Artifacts on the right sidebar and examine.
    ![2021-01-29 18-41-29 的螢幕擷圖](https://user-images.githubusercontent.com/91274/106265215-ab497580-6261-11eb-8fb8-e12c824d5f05.png)

**Expected behavior**
1. The test should pass; or
2. Tests are either pass all the time, or fail all the time. The same source code should not result in occasional pass / fail.

**Your System**
 - Gibbon version v22.0.00 latest
 - Browser PhpBrowser

**Comment by yookoala** [comment]
Here is the list of things that's tested by `ManageActivitiesCept` (to the best of my understanding):

1. Add a new Activity named "T1 Test Activity". Since the dummy data fill up the table until `gibbonActivityID=2335`, the `gibbonActivityID` of this activity must be "00002336".
2. Rename this newly created Activity as "T2 Test Activity".
3. On the "Manage Activities" page, click "Enrolment" to enrol for the activity (**Failed on the enrolment page**).

**Comment by yookoala** [comment]
After further investigation, found something interesting:
1. These seem to be the lines that show the error mesage:
   https://github.com/GibbonEdu/core/blob/c18f0a9fe6fe27fd7f253ea16d966d56d36b836d/modules/Activities/activities_manage_enrolment.php#L43-L45
2. This will show when the program check and see if the current user is an organizer with this query:
    https://github.com/GibbonEdu/core/blob/c18f0a9fe6fe27fd7f253ea16d966d56d36b836d/modules/Activities/activities_manage_enrolment.php#L36-L39
    But I checked my local installation, a newly created activity don't seem to have any organizer, as well.
3. The section above would not even run if this condition is not pass:
    https://github.com/GibbonEdu/core/blob/c18f0a9fe6fe27fd7f253ea16d966d56d36b836d/modules/Activities/activities_manage_enrolment.php#L33-L34
4. It's possible that `getHighestGroupedAction` function returns something randomly so it sometimes pass:
    https://github.com/GibbonEdu/core/blob/c18f0a9fe6fe27fd7f253ea16d966d56d36b836d/functions.php#L764-L785
5. The GitLab CI setup is using `mariadb:latest` as database, while GitHub Actions is using `mysql`. My theory is: the default storage engine of MariaDB somehow ordered the rows differently than the default of MySQL. The return order of MySQL is probably insert-order dependent while MariaDB is not.

    But if that's the case, it is indeed a bug. It is dangerous to rely on the default listing order of the storage engine. Need to dive into the issue more to find out.

**Comment by yookoala** [comment]
I created a new branch to use `mysql:5.7`, instead of `mariadb:latest`, in CI. And I reran the CI a few times. The error never show up again. When using maridb, the error used to show up on 1 out of 3 tests.

**Comment by yookoala** [comment]
As a side issue, I think we need a way to also test different database / version. Will probably add some "includes:" matrix target for that (e.g. php8 + mariadb:10.2, php8 + mariadb:latest, php8 + mysql:latest, php8 + mysql:5.7)

**Comment by SKuipers** [comment]
Hi Koala, interesting bug indeed! I'm not familiar with GitLab, but it's interesting that MariaDB is returning a different result (intermittently!) than MySQL. I have one school using MariaDB in production, they haven't had any issues in general, but I don't know how heavily they use activities.

Grouped actions use a precedent, numerical value, to order the actions before grabbing the highest one, so it's not dependent on the insert order. Which makes the error even more bizarre, a numerical sort should be reliable regardless of version 🤔

**Comment by yookoala** [comment]
@SKuipers: May I ask what does `getHighestGroupedAction()` actually do? The comment describe it as "Looks at the grouped actions accessible to the user in the current module and returns the highest". But I can't really make sense of it. What is the high and low of actions has to do with the permission in enrolment anyway?

**Comment by yookoala** [comment]
By adding logging to the program, I can confirm that the query in `getHighestGroupedAction` doesn't always provide the same order, thus the first row is not always the same:

```mysql
SELECT
  gibbonAction.name
FROM
  gibbonAction,
  gibbonPermission,
  gibbonRole
WHERE
  (gibbonAction.URLList LIKE '%activities_manage_enrolment.php%') AND
  (gibbonAction.gibbonActionID=gibbonPermission.gibbonActionID) AND 
  (gibbonPermission.gibbonRoleID=gibbonRole.gibbonRoleID) AND
  (gibbonPermission.gibbonRoleID='001') AND
  (gibbonAction.gibbonModuleID='0015')
ORDER BY precedence DESC
```

The expected order would be:
```
"Manage Activities"
"My Activities_viewEditEnrolment"
```

But in MariaDB environment, sometimes it gives you this:
```
"My Activities_viewEditEnrolment"
"Manage Activities"
```

As I said before, since the query is "ORDER BY precedence DESC", and both of the mentioned actions has a `precedence` of 0, the return order depends on the database storage engine. This is not reliable.

Instead, we can change `ORDER BY precedence DESC` to `ORDER BY precedence DESC, gibbonAction.gibbonActionID`. Adding the `gibbonActionID` as secondary sorting key makes the result more predictable (and in this case, behaves the same as expected). But this also might introduce another unexpected behaviour to break other parts of system.

**Comment by yookoala** [comment]
Spent some time to find the Innodb default order. I remember, when I first learn about MySQL, the default order is by the ascending order of primary key (such as [this answer](https://stackoverflow.com/a/49826908/372172) described) while MyISAM is by the descending order of insertion / update.

My point is we should not depend on the default ordering of storage engine.

**Comment by SKuipers** [comment]
Thanks for looking into this and providing a solution. Ideally, the precedence will be set on the actions so that they're not identical, so this is also a bug in the Activity Enrolment permission, so I'll also push a fix for that. Your fix looks great, and helps ensure there isn't any ambiguity in the returned row 👍 

Grouped actions exist because certain pages can have multiple levels of permissions controlling them, which are available to certain roles. Eg: some roles can edit all records, some can only edit their own, some are view only, etc.

In terms of testing different platform combinations, is is possible to setup those tests not to run automatically, but manually. I'd rather not slow down the tests with a whole bunch of extra platforms, but it'd be nice to be able to run the tests against them periodically.
