### ISSUE TITLE
Flexible content layout bug

### ISSUE THREAD

**Issue by fvlasie** [GibbonEdu/core#1271]
The resizable/flexible content is really nice but I have encountered an issue where it seems to switch when the window is still too narrow to accomodate the side column properly:

<img width="1042" alt="Screenshot 2021-03-10 at 10 19 37 AM" src="https://user-images.githubusercontent.com/33334298/110678968-c2964f80-818b-11eb-9a6d-994950505a2f.png">

Thank you!

**Comment by SKuipers** [comment]
Thanks Leo for fixing this issue 👍  FV, if you apply this change to your install you should see the calendar scaling better now.
