### ISSUE TITLE
Planner is unaware of school closures

### ISSUE THREAD

**Issue by fvlasie** [GibbonEdu/core#1296]
When entering lesson data in Planner the next-class-slot-detector (i.e. add lesson plan or bump) does not seem to know about school closures. This means that once you hit a school closure the only way to advance to the next class slot is by manually entering the date.

**Expected behavior**
Planner should know to skip dates that have been marked as closures in the timetable.

Thank you! :)
FV

**Comment by SKuipers** [comment]
Hi FV, can you share some steps to reproduce and screenshots? I've checked the code for the planner_bumpProcess.php script and it does look like it's checking for school closures, so I wonder what use-case might result in this not working for you.

**Comment by fvlasie** [comment]
Hello Sandra,
Thanks for the reply!
In Planner I click "Add" to make a new lesson (the last lesson entered is 12/05/21):

<img width="846" alt="Screenshot 2021-04-11 at 7 13 18 pm" src="https://user-images.githubusercontent.com/33334298/114332150-76c42680-9afa-11eb-9485-c829c86b276f.png">

The lesson creating page autofills a date of 26/04/21:

<img width="862" alt="Screenshot 2021-04-11 at 7 13 35 pm" src="https://user-images.githubusercontent.com/33334298/114332226-a2471100-9afa-11eb-98cc-1fade97db6d1.png">

But that week school is closed:

<img width="779" alt="Screenshot 2021-04-11 at 7 13 52 pm" src="https://user-images.githubusercontent.com/33334298/114332251-b1c65a00-9afa-11eb-90d2-4901c6bd5d64.png">

**Comment by SKuipers** [comment]
Thanks FV for the screenshots and the steps 👍  I can see now that it's not the bump action but the add action that needed fixed. I've applied this fix to v22, which you can see here: https://github.com/GibbonEdu/core/commit/a2af15b620d1e14ab8b50e9b5c7a8004854e1649
