### ISSUE TITLE
Suggestion: Automated Attendance

### ISSUE THREAD

**Issue by nobicycle** [GibbonEdu/core#13]
(I was not sure whether to enter this suggestion as an issue).

Suggestion:
Use automated attendance information gathering.

Benefit:
1.Leaves the teacher to attend to the class instead of being focused on mundane attendance register. 
2.Data is electronic and cannot be lost is falsified.
3.The categories (Late etc) are calculated.
4.No time lost in Data entry.
 
I am using this fingerprint reader:
Bus 001 Device 011: ID 05ba:000a DigitalPersona Inc. Fingerprint Reader
URU4000 driver
45 USD on Aliexpress.com

This is compatible on all platforms, but in particular Android tablets.

Using this app (insert some names manually):

https://gitorious.org/employee-time-clock-with-fingerprint-reader/employee-time-clock-with-fingerprint-reader/source/e3a5201da43e168c95f9f1eea22495cfbff01a3f:bin/timeclock

, after training with about 4 scans, the  recognition was 10 out of 10.

**Comment by rossdotparker** [comment]
nobicycle, thanks for this suggestion, it does sound good. Certainly an improvement on card scanners, which are far easier to spoof. At this point, we have a range of priorities, so I can't see this being implemented on our side. However, if you wanted to code it up, we would certainly look at merging it into the core. Thanks for taking the time to make this suggestion.
