### ISSUE TITLE
"You do not have Full or Write access to any budgets"

### ISSUE THREAD

**Issue by TirushV** [GibbonEdu/core#1394]
![Screenshot (348)](https://user-images.githubusercontent.com/84138572/129240355-13c49ec7-5d05-4852-8347-9a7738bbb297.png)
Sir, Can you please help me how to fix this?

**Comment by rossdotparker** [comment]
Hi Tirush,

Thanks for your email, and welcome to the Gibbon community. We are currently directing such enquiries to our support forums. Please start by searching the forum for answers to these questions. If you cannot find the information you need, post each question as a new forum thread, and we will answer the question there. We prefer the forum, as it helps keep answers public and accessible to other users.

Another option is Expert Support via gibbonedu.com. If you would like to set up a Zoom call or email conversation, to work through your issues, please let us know and we can advise on pricing.

**Comment by yookoala** [comment]
@TirushV: For your information, the URL to the support forum is: https://ask.gibbonedu.org/

**Comment by rossdotparker** [comment]
Thanks @yookoala, not sure why the link did not copy across!
