### ISSUE TITLE
How to generate fee related reports for students  

### ISSUE THREAD

**Issue by TirushV** [GibbonEdu/core#1397]
Please kindly help us by sharing any other documentation regarding this or any suggestion

**Comment by yookoala** [comment]
Hi Tirush,

Thanks for your email, and welcome to the Gibbon community. We are currently directing such enquiries to our [support forums](https://ask.gibbonedu.org/). Please start by [searching the forum for answers to these questions](https://ask.gibbonedu.org/search?Search=generate+reports). If you cannot find the information you need, post each question as a new forum thread, and we will answer the question there. We prefer the forum, as it helps keep answers public and accessible to other users.

Another option is [Expert Support via gibbonedu.com](https://gibbonedu.com/). If you would like to set up a Zoom call or email conversation, to work through your issues, please let us know and we can advise on pricing.
