### ISSUE TITLE
Is it FERPA compliant?

### ISSUE THREAD

**Issue by ugintl** [GibbonEdu/core#1430]
Is GibbonEdu FERPA compliant?

**Comment by yookoala** [comment]
Hi @ugintl,

Thanks for your question, and welcome to the Gibbon community.

I have limited knowledge to [FERPA](https://www2.ed.gov/policy/gen/guid/fpco/ferpa/index.html), so it's not obvious to me as to what is "FERPA compliant". Please kindly put your question on our [support forums](https://ask.gibbonedu.org/) or [searching the forum for answers to these questions](https://ask.gibbonedu.org/search?Search=FERPA). There might be other educator / developer with similar concerns that can help you with it. We prefer the forum, as it helps keep answers public and accessible to other users.

Another option is [Expert Support via gibbonedu.com](https://gibbonedu.com/). If you would like to set up a Zoom call or email conversation, to work through your issues, please let us know and we can advise on pricing. We might even help you in developing Gibbon towards FERPA compliance as a type of support. Please consider supporting the project.

**Comment by ugintl** [comment]
@yookoala What does it mean to be FERPA compliant?
FERPA provides parents or eligible students the right to inspect, review and request changes to be made to education records maintained by the school. Parents or eligible students have the right to prohibit schools from disclosing directory information, in addition to PII which is already prohibited from disclosure
