### ISSUE TITLE
Import Error on System Admin 

### ISSUE THREAD

**Issue by hanattaw** [GibbonEdu/core#1453]
**Describe the bug**

When import data from file , there is an error on import field that data type not specific length from "SHOW COLUMNS FROM <tablename>" e.g. gibbonString. 

**To Reproduce**

1. Go to 'System Admin'
2. Click on 'Import From File' Menu
3. Scroll down to 'SYSTEM ADMIN' Section
4. Select 'Settings category' > 'String Replacment' > Export Columns
5. Fill some data on excel. Especially for 'Priority' set the data to some integer e.g. 1
6. Back to upload excel.
4. Submit the process until 'Dry Run' Process
5. see error 'Invalid value: "1". Expected: Number'

**Expected behavior**

Dry Run process should pass.

**Screenshots**

<img width="976" alt="image" src="https://user-images.githubusercontent.com/3141235/134899281-aff9705c-2c3a-4a25-9ad9-82982abcca17.png">

**Your System**

 - Gibbon version:  v21.0.03, v22.0.01
 - MySQL version: 8.0.21
 - Browser:  chrome, safari

**Additional context**

After check code, src/Data/ImportType.php
Function parseTableValueType()

We should check the $type and $details again the $details if empty.

After find out, we see deprecated in MySQL 8.0.17  'Data type definitions of the int will no longer show width'

![mysq8017](https://user-images.githubusercontent.com/3141235/134899519-07c13cf2-a427-4565-be16-068dcc0d2c61.png)

**Comment by SKuipers** [comment]
Thanks for bringing this to our attention, it does look like an interesting bug that MySQL 8.0.17 has introduced. I've put a basic fix in place for v23, which you can see here any apply to your own codebase: https://github.com/GibbonEdu/core/commit/0b29e931f00c7147907a02f7492ce1e6a961766d  I don't have access to MySQL 8.0.17+ at the moment to test it, but it should do the trick.
