### ISSUE TITLE
Errors occurred in populating the database

### ISSUE THREAD

**Issue by petrk94** [GibbonEdu/core#156]
Hello,
Im trying to install GibbonEdu on a shared server of Uberspace.
The install works and I can enter the database informations, but than I get this message:

Errors occurred in populating the database; empty your database, remove ../config.php and try again.

What can I do to solve this problem?
thanks

**Comment by rossdotparker** [comment]
Hello,

For this kind of issues, with are more likely to do with server configuration and less likely to be bugs, we are directing queries to our forum. Please can you post the same question at https://ask.gibbonedu.org and we will answer it there? Thanks!

Ross
