### ISSUE TITLE
update the /vendor/tecnickcom/tcpdf

### ISSUE THREAD

**Issue by taha-mahmoud-ly** [GibbonEdu/core#1562]
**Describe the bug**

tcpdf causes a fatal error with PHP8 as numeric curly braces are no more allowed(  already depricated in PHP7.4) .

it needs to be updated with the latest version

**Comment by SKuipers** [comment]
Hi @taha-mahmoud-ly Thanks for your message. We've already updated TCPDF in the current development version of Gibbon, v23, which will be released in January 2022. You can find the changes in following pull request: https://github.com/GibbonEdu/core/pull/1434 Thanks!
