### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by JamieSlome** [GibbonEdu/core#1596]
Hey there!

I belong to an open source security research community, and a member (@truonghuuphuc) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by SKuipers** [comment]
Hi @JamieSlome 

Thank you for your message. Yes, we had received this report from @truonghuuphuc via email to support@gibbonedu.org and had already responded to them promptly (within 24 hours). There was an additional report in the Issue tracker which we removed, in keeping with best practices for not reporting vulnerabilities publicly until the development team has had a chance to review and patch the issue.

We're happy to work on adding a SECURITY.md file to our project to help future contributors.

Thanks,
Sandra

**Comment by SKuipers** [comment]
We have now added a [SECURITY.md](https://github.com/GibbonEdu/core/security/policy) file. Thanks!
