### ISSUE TITLE
Failed to apply utf8mb4 and only support utf8 in Home > User Admin > Manage Users > Edit User 

### ISSUE THREAD

**Issue by arthurtalkgoal** [GibbonEdu/core#1598]
In Home > User Admin > Manage Users > Edit User , I tried the utf8mb4 char which failed to be stored:

**𦾾** is utf8mb4 supported but not in utf8

I did tried the command in mysql query to test the result in gibbon:

```update  gibbonPerson set nameInCharacters="余東𦾾" where username = "myuser1" limit 1;```

The database successful show the words in utf8mb4 but failed in gibbon, instead it becomes a **"?"**

And if I type the word **𦾾** in gibbon and save, the mysql col will store **"????"** instead.

```
My versions:
gibbon $version = '19.0.00';

mysql:
Server version: 5.7.36-0ubuntu0.18.04.1 (Ubuntu)

the gibbonPerson.nameInCharacters col setting:
| nameInCharacters           | varchar(120)                                          | utf8mb4_unicode_520_ci | NO   |     | NULL 

```

**Comment by SKuipers** [comment]
Hi @arthurtalkgoal thanks for your message. As you've seen, Gibbon doesn't support utf8mb4 by default, and while it is a development goal for us, we've identified a number of changes we'd need to make to work towards that in future versions.

As you're testing this change on your system, be sure to not only change the collation of the column itself, but also the database collation, which tends to be utf8_general_ci by default. There is also a Server Connection Collation setting in MySQL which will likely need to be changed in your local configuration: https://dev.mysql.com/doc/refman/8.0/en/charset-connection.html

**Comment by arthurtalkgoal** [comment]
Thanks @SKuipers and the information. Can I ask that you mentioned `Gibbon doesn't support utf8mb4 by default` so that if I did the changes in mysql including the DB default charset and collation (which I did for the column only so far), then Gibbon should be able to allow the utf8mb4, is that correct? (or I need to change some PHP coding too, at least in the edit user page?)

Since it is a blocker to the school usage that around 5-10 students have the utf8mb4 chars in their name. 

Thanks a lot.

**Comment by SKuipers** [comment]
Hi Arthur, it just means we haven't had the capacity yet to investigate migrating the whole system over to using utf8mb4. Be sure to update your database and table charset, also check out the post here for changes to make to the MySqlConnector class: https://github.com/GibbonEdu/core/issues/1583. Hope this helps!

**Comment by SKuipers** [comment]
I'm closing this PR for now, utf8mb4 support has been added to the v24 roadmap. Thanks!
