### ISSUE TITLE
Any docker image?

### ISSUE THREAD

**Issue by C-Fu** [GibbonEdu/core#1618]
### Problem

As per title. Having a docker image tremendously helps with the install and setup. Please consider.

The ones that I found are really old and not maintained anymore.

### Proposed Solution

A docker image would help

**Comment by SKuipers** [comment]
Hi @C-Fu It looks like one of our community members has setup a docker image, you can check it out here: https://github.com/PaulLebmann/docker-gibbonedu  Hope this helps!
