### ISSUE TITLE
Discussion: nationalIDCardNumber missing in v22.0?

### ISSUE THREAD

**Issue by arthurtalkgoal** [GibbonEdu/core#1619]
### Problem

I just updated to v22 but the `nationalIDCardNumber `in my `gibbonPerson` seems removed as it was in the v21 coding? this field is very important to my school's data. 

### Proposed Solution

I think it should be stored in some description field and it is very critical for the data records and history

**Comment by rossdotparker** [comment]
Hi Arthur, this is related to line 23 in the v22 CHANGELOG.txt file: https://github.com/GibbonEdu/core/blob/v22.0.00/CHANGELOG.txt

This version of Gibbon introduces a much more flexible system for handling documents, and so whilst that field has gone, the data has not. In the database you can find this under the table gibbonPersonalDocument, and in the interface, you can manage your document types in Admin > User Admin > Personal Document Settings. You'll then be able to use these types with individual users under Manage Users.

Hopefully this helps explain what has changed, and please accept our apologies for any confusion or worry caused.

**Comment by arthurtalkgoal** [comment]
Thanks @rossdotparker I figure out how to do the sql update on the related tables and fields now. Thanks again!

**Comment by rossdotparker** [comment]
Thanks great to hear, thanks for letting us know...and you are most welcome : )
