### ISSUE TITLE
Discussion: Arabic months names translation fix

### ISSUE THREAD

**Issue by azizly** [GibbonEdu/core#1631]
### Problem

Good day gibbon team, this is Abdelaziz, I have been helping in Arabic translation for Gibbon for a while,  I want to bring to attention that the translation used for Arabic month names in gibbon is not the best translation out there, it is using a special translation that is used in only couple Arabic speaking countries, while others find it hard to understand which month is which. 

### Proposed Solution

To use literal translation for the months' names from English to Arabic, which is the practice used all over internet.
Please copy the following text, and paste in a CSV file, then open using Excel, and it will give you tables with correct data.

`No.,Month,Arabic name
1,January,يناير
2,February,فبراير
3,March,مارس
4,April,أبريل
5,May,مايو
6,June,يونيو
7,July,يوليو
8,August,أغسطس
9,September,سبتمبر
10,October,أكتوبر
11,November,نوفمبر
12,December,ديسمبر
`

### Additional Context

I tried to update the translation on https://poeditor.com/ but it is not possible, i think this data needs to be updated on the database.

**Comment by SKuipers** [comment]
Thanks Abdelaziz for opening this discussion and flagging this issue, we're keen to support the internationalization of Gibbon in many different regions and languages. Thank you also for your translation work! 😃 

Are you able to help indicate some specific areas of the system where you are seeing the month names used in this way? I wonder if this may be related to the built-in PHP date translation functions, which may be why changing them in POEditor did not help. If you're able to post some screenshots this may help me as I look into the respective areas of the codebase.

Much appreciated!

**Comment by azizly** [comment]
Hi Sandra, Happy to help always, the mentioned translation is in the Date picker everywhere in Gibbon. 
when picking a date of birth, a date of starting school, a date for attendance.
basically whenever the windows pops out to choose a year, month, and date.

**Comment by yookoala** [comment]
> Hi Sandra, Happy to help always, the mentioned translation is in the Date picker everywhere in Gibbon. 
> when picking a date of birth, a date of starting school, a date for attendance.
> basically whenever the windows pops out to choose a year, month, and date. 

@azizly Would it be possible if you send us a few screenshot of the datepickers you mentioned?

**Comment by azizly** [comment]
![1](https://user-images.githubusercontent.com/95902542/188622585-b4d53816-ea60-4688-b615-3fa5a3e64556.png)
Hi, here is one, in the home page, on the dashboard, when showing the planner and time schedule. 

![2](https://user-images.githubusercontent.com/95902542/188622587-2f776801-07fa-4429-a257-bc7734cf4d31.png)
Second one, when choosing starting or leaving date for a student, (full, left)



![3](https://user-images.githubusercontent.com/95902542/188622578-c40079ba-a08e-4ef1-b124-f058ff9f0968.png)

This one when you chose the birthday for a student.

**Comment by yookoala** [comment]
Gibbon is bundling jQuery UI v1.11.4 and using [its datepicker](https://jqueryui.com/datepicker/) for the job. The translation is in their repository. They have 2 translation files for Arabic:
* https://github.com/jquery/jquery-ui/blob/1.11.4/ui/i18n/datepicker-ar.js
* https://github.com/jquery/jquery-ui/blob/1.11.4/ui/i18n/datepicker-ar-DZ.js

Can you please check if the faulty Arabic month names are originated in either of this file?

**Comment by azizly** [comment]
Hello @yookoala , I am sorry for my late reply. 
The month names in: https://github.com/jquery/jquery-ui/blob/1.11.4/ui/i18n/datepicker-ar.js  
are perfect, please replcae the current ones on gibbon with those.

The one used in gibbon currently is neither one of both links you sent, it's rather another form of translation that is mostly used in Lebanon  and called "Assyrian calendar"  please read more about it here: https://en.wikipedia.org/wiki/Assyrian_calendar


the one i am recommending to use is in the second table in this link: https://en.wikipedia.org/wiki/Arabic_names_of_Gregorian_months
a translation for Gregorian months (also in the first link you sent in your last comment).

**Comment by yookoala** [comment]
@azizly Thanks for the reply.

I'd like to be sure where the problem started before formulating a fix.

The language file used by Gibbon is this one:
https://github.com/GibbonEdu/core/blob/323307e6b78bc5c6d94e704fa081bdff90398806/lib/jquery-ui/i18n/jquery.ui.datepicker-ar.js

Can you please check if the file is the source of the translation issue?

**Comment by azizly** [comment]
> @azizly Thanks for the reply.
> 
> I'd like to be sure where the problem started before formulating a fix.
> 
> The language file used by Gibbon is this one: https://github.com/GibbonEdu/core/blob/323307e6b78bc5c6d94e704fa081bdff90398806/lib/jquery-ui/i18n/jquery.ui.datepicker-ar.js
> 
> Can you please check if the file is the source of the translation issue?

Yes, this is it, the file is using "Assyrian calendar" as mentioned in my previous comment, please replace it with the file in https://github.com/jquery/jquery-ui/blob/1.11.4/ui/i18n/datepicker-ar.js
and it should be prefect and good to go with  Gregorian translation.

**Comment by SKuipers** [comment]
Thanks Abdelaziz for your help and Koala for finding and creating a fix, great to see this issue addressed 😃 This is now [merged into v25](https://github.com/GibbonEdu/core/commit/780101a57194756f0dad606a3876c4343c4cd0ee). Abdelaziz, you're welcome to apply the same changes to your installation and hopefully you should see improved date translations.

**Comment by azizly** [comment]
Updated the code on my installation and it works like a charm, thank you everyone.
