### ISSUE TITLE
Bug: Copy to next Year

### ISSUE THREAD

**Issue by KelvinMW** [GibbonEdu/core#1632]
### Describe the Bug

The function copy to next year under **school admin>> Manage Form groups** 
does not check for duplicate of form group short name and if copy to next year is clicked multiple times it **populates next year with duplicate form groups**

### To Reproduce

Go to : School Admin
on Left side Menu: Manage Form Group
then 
Click copy Form Group to next year (click several times)

### Expected behavior

To detect multiple Duplicates of Form Groups in that Year(current-year+1)
to avoid duplicates on the (current-year+1) academic year.

### Actual behavior

Duplicates are produced when you switch to (current-year+1)

### Gibbon version

v24

**Comment by SKuipers** [comment]
Hi Kelvin, thanks for the heads up! I've fixed this in v25 in the following commit, which is backwards compatible to v24: https://github.com/GibbonEdu/core/commit/09289a53743457122a6b44a1671a5eedcf938baa
