### ISSUE TITLE
Bug: Timetable "tool tip" popup show in wrong column

### ISSUE THREAD

**Issue by fvlasie** [GibbonEdu/core#1640]
### Describe the Bug

The "Add Lesson Plan" popup is showing in the wrong column.
(I know it seems nitpicky but these little interface quirks raise doubt in the end user's minds about the system in general.)

### To Reproduce

Go to the Timetable in the capacity of teacher and hover the mouse over the "+" sign.

### Expected behavior

Popup should appear above the mouse.

### Actual behavior

Popup appears in previous column

### Screenshots

<img width="833" alt="Screenshot 2022-09-13 at 12 00 57 AM" src="https://user-images.githubusercontent.com/33334298/190703721-4d736dd7-ed1d-4bbf-9b9d-9a938ad0f850.png">

### Gibbon version

25

### Browser

Safari

### Browser Version

16

### Additional Context

PHP 8

**Comment by SKuipers** [comment]
No problem, looks like this was a quick fix which I've committed to v25 here: https://github.com/GibbonEdu/core/commit/f0205b33501e085b8966bf3d67ef196cac899174

**Comment by fvlasie** [comment]
Thank you again!
