### ISSUE TITLE
Calendar does not display on days school is not in session

### ISSUE THREAD

**Issue by dowens76** [GibbonEdu/core#165]
I have our school calendar (on Google) set to show up on the home page of a gibbon user.
![screencapture-regular-days](https://cloud.githubusercontent.com/assets/170327/22579051/c86bb328-e9ff-11e6-8e51-f7ad51bd13a7.png)

I noticed that on days that are marked as not in session, the calendar does not display even though those days are marked on the calendar as the mid-semester break. 
![screencapture-school-closed](https://cloud.githubusercontent.com/assets/170327/22579055/d526e998-e9ff-11e6-956e-6cc643b6f77f.png)

It is desirable that these days show up so that users would know why there is no class scheduled that day (e.g., there is a break that day). I had a teacher ask me about it. I had to show him the Google calendar in another place to confirm that was the reason.

This relates to version 13.

**Comment by rossdotparker** [comment]
Daniel, that is an interesting one. The day's marked as "not in session", they seem to be in term time, without timetable days tied to dates, and without special days, is that correct? I believe if they are out of term time, or if they have special days, or if they have days tied to dates, then they should appear. Can you do a little testing to confirm this, and let me know, then we can look into this edge case? Thanks! Ross.

**Comment by dowens76** [comment]
Yes, they are in term time without timetable days tied to dates. 

Days tied to dates show events in the calendar (see my first screenshot above). 

Days out of term time show:
![screencapture-gib-hbc-edu-vn-index-php-1486172140399](https://cloud.githubusercontent.com/assets/170327/22614480/06e6ce52-eab5-11e6-815b-a470ec299082.png)

But are special days defined in Gibbon? How would I do that?

**Comment by rossdotparker** [comment]
OK, that helps! Special days are days where school is closed or timings are changed. You can set these up under Admin > School Admin in the main menu followed by Manage Special Days in the module menu. If you add special days to the days in question, does that help solve your issue?

**Comment by dowens76** [comment]
Yeah, okay, the problem was I did not configure special days. Now it works. Sorry about that.

**Comment by rossdotparker** [comment]
I guess it should work without special days...will try and fix this one of these days. Ross.

**Comment by dowens76** [comment]
I think documentation is one piece of this. There are some ways we could improve that, and since I am fresh as a user, I can try to work on that. I need to remember what I did for next time anyway!

Let me say when I realized there was a setting for special days and managing them was so easy, it only increased my delight in Gibbon. You've really done a good job putting it together.

**Comment by rossdotparker** [comment]
Daniel, yes, documentation continues to be our weakest link...something I hope to remedy in the future. In the past, and for the immediate future, all effort has gone into features, stability and security. Glad to hear you are delighted by Gibbon : )
