### ISSUE TITLE
Markbook Average Display

### ISSUE THREAD

**Issue by jcarney2024** [GibbonEdu/core#1716]
### Describe the Bug

The "Class Average" box is incorrectly formatted when there are no marks yet entered. The Class Average text gets cut off, because it's too short.

### To Reproduce

1. Go to Learn -> Markbook
2. Select a class without any Columns / entered marks
3. See the ‘Class Average’ box incorrectly formatted

### Expected behavior

I would expect the box to fit correctly around the ‘Class Average’ box, without it getting cut off. 

### Actual behavior

The box is cutting off the text. It’s not long enough. 

### Screenshots

![B2D19E85-CE5C-455C-ABD4-80C5FBB096EB](https://user-images.githubusercontent.com/75650821/217627942-7b780474-baf5-479a-9098-1e6d84cac998.png)

### Gibbon version

v26.0.00

### Browser

Chrome

### Browser Version

CHROME VERSION: 110.0.5481.78 on Windows 10 Enterprise

**Comment by SKuipers** [comment]
Thanks @jcarney2024, fixed in v26: https://github.com/GibbonEdu/core/commit/6e42f28f66f73de815d388e20d0b923385b735d3 👍
