### ISSUE TITLE
Messenger's Home Screen Widget breaks the render of the sidebar

### ISSUE THREAD

**Issue by taha-mahmoud-ly** [GibbonEdu/core#1718]
### Describe the Bug

When the  **Home Screen Widget** is enabled in the **MESSAGE WALL SETTINGS** ( School Admin >> Messanger Settings ), The Home screen sidebar fails to render, giving a warning of something escaped.

### To Reproduce

1. go to Admin >> School Admin >> Messanger Settings >> MESSAGE WALL SETTINGS >> enable Home Screen Widget

### Expected behavior

The message walls appear on the sidebar as a quick preview.

### Actual behavior

The sidebar fails to render. checking the logs it shows this error

FastCGI sent in stderr: "PHP message: Uncaught Exception: InvalidArgumentException - Query and fragment must be a string in /var/www/html/vendor/guzzlehttp/psr7/src/Uri.php on line 772"

### Gibbon version

V25

### Browser

None

### Additional Context

disabling the homescreen widget gives a well rendered home screen.

**Comment by leofreitas** [comment]
I was unable to reproduce this bug. @taha-mahmoud-ly, can you test again and send a screenshot please?

**Comment by taha-mahmoud-ly** [comment]
### Here it's.
_with the Home screen widget enabled in Messenger settings. Post a new wall message and go to Home.
the bug shows both in Arabic and English versions of the site.
my environment: Alpine-based PHP-Nginx Docker container behind a traefik loadbalancer._
-----------------------------------------------------------------
**Home  with widget disabled (Note the message notification )**
![Screenshot from 2023-06-07 19-18-10](https://github.com/GibbonEdu/core/assets/52387448/4172c59a-02bb-4b0e-b0fe-0e9cee1f5986)

----------------------------------------------------------------
**Home with widget enabled (Sidebar fails to render)**
![Screenshot from 2023-06-07 19-15-54](https://github.com/GibbonEdu/core/assets/52387448/8d79a3d1-a612-414f-bdaa-9020aaf78fdf)
-----------------------------------------------------------------
**Home with widget enabled and no wall Messages (notice the off message notification)**
![Screenshot from 2023-06-07 19-29-41](https://github.com/GibbonEdu/core/assets/52387448/1e73aea3-c140-4a57-ac87-4dec950a9efd)

**Comment by leofreitas** [comment]
What version of php?

**Comment by taha-mahmoud-ly** [comment]
> What version of php?

PHP Version
8.1.18

**Comment by SKuipers** [comment]
Thanks @taha-mahmoud-ly I'm just circling back to some of the open issues and I think this issue has since been fixed here: https://github.com/GibbonEdu/core/commit/7ca4d27dbe15c2f6b07d54aaf9cbf81f504825e6. Please do let us know if the error persists, thanks.
