### ISSUE TITLE
Bug: Change in language crashes GibbonEdu language admin pages

### ISSUE THREAD

**Issue by dom-madrid** [GibbonEdu/core#1747]
### Describe the Bug

I installed GibbonEdu with multiple language starting from English. I installed the french package, made sure fr_FR locale was installed (on Ubuntu 22.04 LTS server) and switch my user to french. The result is that I can no longer change language as the admin language page return a monkey escaped error. 

### To Reproduce

Install the french  (in both the system and GibbonEdu)
Go to the manage language
Change to French as default language
Logout/Login
You in French now
Go to the manage language
... Escaped Monkeys

### Expected behavior

Install the french  (in both the system and GibbonEdu)
Go to the manage language
Change to French as default language
Logout/Login
You in French now
Go to the manage language
Change your language to your liking

### Actual behavior

Install the french  (in both the system and GibbonEdu)
Go to the manage language
Change to French as default language
Logout/Login
You in French now
Go to the manage language
... Escaped Monkeys

### Screenshots

![image](https://user-images.githubusercontent.com/5640062/232554904-42badb6b-0575-4afc-81b1-6c7995abe63e.png)

### Gibbon version

25.00

### Browser

Other (specify below)

### Browser Version

Opera Version:97.0.4719.63

**Comment by yookoala** [comment]
Do you have server logs (Apache / php-fpm) when the error happened?

**Comment by dom-madrid** [comment]
Both access.log and error.log are attached.

[gibbonedu_french.zip](https://github.com/GibbonEdu/core/files/11253390/gibbonedu_french.zip)

**Comment by dom-madrid** [comment]
While I kept on browsing the application, the same error occured in the Staff section, sub section reports: the second, third and fourth report generate monkeys as well. And it seems the errors in the apacle log are different. So, here is another copy.

I'll keep reviewing the other tabs to identify more of that problem.

[gibbonedu_french_2.zip](https://github.com/GibbonEdu/core/files/11254174/gibbonedu_french_2.zip)

**Comment by dom-madrid** [comment]
So, I found a few others:
- individual needs fin archive
- attendance reports class not registered
- attendance reports group not registered

**Comment by leofreitas** [comment]
@dom-madrid Can you test with another language besides French? It looks like the error is related to the permissions on the folders in your installation.

**Comment by dom-madrid** [comment]
Hi, I did an engligh install before and it worked correctly. I then went on activating the french langiage pack. The problem now is that I cannot  go back to another language since the manage language section is being in error. If it is a permission problem, can you point to which one and what permissions should I set ? My only alternative is to reinstall from scratch and try another language (apart from english).

**Comment by Geekst3r** [comment]
> Hi, I did an engligh install before and it worked correctly. I then went on activating the french langiage pack. The problem now is that I cannot go back to another language since the manage language section is being in error. If it is a permission problem, can you point to which one and what permissions should I set ? My only alternative is to reinstall from scratch and try another language (apart from english).

Hi. Were you ever able to resolve this issue?

If you have access to the gibbon database, can you edit the gibboni18n table and change the active, installed, and systemDefault flags to Y. This should take you back to the default English language.

If the above step is successful, you can now access system admin. proceed to do language pack updates for all languages to ensure that all language packs are fully downloaded. After which, try to change to the French language again to see if the bug can be repeated.

**Comment by dom-madrid** [comment]
Hi,

Good news. The steps you provided actually solved the problem. I can now switch between languages after updating the languages packs. I successfully switch between several times between english, french, spanish and italian.

The described bug is fixed.

However, as a side note, I found something peculiar in the 'System Overview'. When the text says 'system overview' (for the english and Italian languages - the latter one not being translated), the system retrieves correctly that I need to update the application. When using the french or spanish language pack, the 'System Overview' is translated in the desired language, but the update information is stuck as you see in the screen print:
![image](https://github.com/GibbonEdu/core/assets/5640062/ebcd3918-c7b7-4454-9713-2234269cc01f)
If I switch back to english it works.
![image](https://github.com/GibbonEdu/core/assets/5640062/f2612755-3b0d-48a7-be3f-13a8787efbda)

It seems is still missing somewhere...

**Comment by Geekst3r** [comment]
> Hi,
> 
> Good news. The steps you provided actually solved the problem. I can now switch between languages after updating the languages packs. I successfully switch between several times between english, french, spanish and italian.
> 
> The described bug is fixed.
> 
> However, as a side note, I found something peculiar in the 'System Overview'. When the text says 'system overview' (for the english and Italian languages - the latter one not being translated), the system retrieves correctly that I need to update the application. When using the french or spanish language pack, the 'System Overview' is translated in the desired language, but the update information is stuck as you see in the screen print: ![image](https://user-images.githubusercontent.com/5640062/278424327-ebcd3918-c7b7-4454-9713-2234269cc01f.png) If I switch back to english it works. ![image](https://user-images.githubusercontent.com/5640062/278424970-f2612755-3b0d-48a7-be3f-13a8787efbda.png)
> 
> It seems is still missing somewhere...

Hi.

I cannot replicate that behavior. Can you please update the core installation to version 25.0.01, as this is the latest stable release version of gibbon. As earlier pointed out, the majority of these can be related to the installation being incomplete.

Regards

**Comment by dom-madrid** [comment]
Hi,

I just reinstalled a full Gibbon in order to test directly the latest version (26.0.0). I'll close this issue and open a different one.

**Comment by leofreitas** [comment]
@dom-madrid, but the problem remains?
