### ISSUE TITLE
Bug: Timetable time slot detection failure

### ISSUE THREAD

**Issue by fvlasie** [GibbonEdu/core#1847]
### Describe the Bug

Auto-fill for date and time does not advance properly when adding lessons in the planner.
1) When a lesson has been submitted Gibbon used to present the lesson editor with fileds prefilled for the next time slot. Now the time slot stays the same requiring manual entry to be correct.
2) Clicking on the "+" to add a lesson in Year Overview does not load the date and time slot of the chosen slot.

### To Reproduce

1. Go to Planner
2. Choose a Class
3. Add+ a lesson
4. Submit

### Expected behavior

The new "empty" lesson page should have the date and time entered for the next slot. 

### Actual behavior

The new "empty" lesson page has the date and time slot of the lesson just saved. 

### Screenshots

https://github.com/user-attachments/assets/9ab571af-202c-468f-89d2-c13a564b0589

### Gibbon version

28

### Browser

Safari

### Browser Version

Safari 17.6, MacOS Sonoma 14.6.1

### Additional Context

Replicated the bug in a fresh install of 28.
Replicated the bug in Safari on MacOS.
Replicated the bug in Firefox on MacOS.

**Comment by SKuipers** [comment]
Thanks @fvlasie for the detailed bug report. I've found and fixed the issue for v28, and you are correct that it was related to the new autosave feature. Luckily, it's a quick fix to apply to your system, which can be found here: https://github.com/GibbonEdu/core/commit/7a8ea4eb01a3aa0a77c28914c13e378c741a23fd

**Comment by fvlasie** [comment]
Thank you!
