### ISSUE TITLE
Error Adding Fees

### ISSUE THREAD

**Issue by jmsperu** [GibbonEdu/core#19]
I received an error when I was trying to add fees.Please refer to the attached image and advice on how to address the issue. Thank
![err](https://cloud.githubusercontent.com/assets/10476367/7670180/bad2a798-fc4f-11e4-99f2-600f5445361e.PNG)
 you

**Comment by rossdotparker** [comment]
This has been fixed in v10 (which is in the v9.2.00 branch here on GitHub). As advised by email, you are best of running with PHP Notices turned off to avoid such issues. If you do spot any more of these, let us know and we will fix them up for the next version.

**Comment by jmsperu** [comment]
I turned error reporting off and they are not displaying any more. Thank you.

On 5/17/15, Ross Parker <notifications@github.com> wrote:
> Closed #19.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/GibbonEdu/core/issues/19#event-307055487


-- 
Thank you, Best Regards,
James M. Peru
