### ISSUE TITLE
Print button for custom sql reports

### ISSUE THREAD

**Issue by mwendwa5** [GibbonEdu/core#223]
Can we have a print button for custom sql reports in query builder?

**Comment by rossdotparker** [comment]
Bruce, printing unknown numbers of rows and columns presents a number of headaches, especially with web based systems. For printing I would recommend you export to a spreadsheet, and then use a spreadsheet app, which will have far more fine-grained print controls to do this.

For future reference, please post questions on Additional modules in the relevant repoistory for that module (this repository is only for Gibbon Core, including Core modules. In the case of Query Builder, the repo is:

https://github.com/GibbonEdu/module-queryBuilder

Thanks, and sorry we can't do more for you in this case.

Ross
