### ISSUE TITLE
Cannot change Invoice status without entering an imaginary 0 amount

### ISSUE THREAD

**Issue by mwendwa5** [GibbonEdu/core#225]
I wanted to change status of invoice since the fee paid in full. However this is not possible unless I make an imaginary payment of 0 amount. See attached screenshots.

![selection_385](https://cloud.githubusercontent.com/assets/4364019/25774227/6872acaa-3294-11e7-8219-4b75620360fc.png)

![selection_386](https://cloud.githubusercontent.com/assets/4364019/25774245/a8329a4e-3294-11e7-9f53-9f066baa564b.png)

**Comment by rossdotparker** [comment]
Bruce, the way it is designed is that any payments made up until the point where the outstanding amount reaches $0 are Partial...but the final payment you make should have an amount and should be Final. Hope this makes sense.
