### ISSUE TITLE
Automatic change of invoice status

### ISSUE THREAD

**Issue by mwendwa5** [GibbonEdu/core#226]
Can Invoice change status automatically after some payment has been received? e.g. if a partial payment is received, can it change to Paid-Partial and when full payment is made, to Paid?

**Comment by rossdotparker** [comment]
We could do this, but sometimes people pay less than the full amount (perhaps a fee is optional, or they dispute something) and the computer would logically guess that it is a partial payment, but an operator knows it to be a full payment. This was why we implemented the way we did. Not to say it is perfect....but it works in many cases.
