### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by jackdickson5390** [GibbonEdu/core#282]
When hovering over a behavioural referral in the roll group section of the staff dashboard, the tick for positive referral says 'Position' rather than 'Positive'

**Comment by rossdotparker** [comment]
Jack, well spotted. Surprised this one was never spotted before. It has been fixed in the following commit to the v14 dev branch: 0f32db8ea484b8b4ba827b96fb35e8be806c446e

Thanks,

Ross

**Comment by jackdickson5390** [comment]
I didn't know if this was appropriate to report spelling mistakes and was trying not to be smarmy about it. I just want to help. Thanks & good luck for v14 release! We're waiting!

**Comment by rossdotparker** [comment]
Perfect use of this feature : ) Not smarmy...helpful! Cheers.

**Comment by rossdotparker** [comment]
Perfect use of this feature : ) Not smarmy...helpful! Cheers.

v14 will be out on time...perhaps even a day or two early. All lined up and ready to go!

**Comment by jackdickson5390** [comment]
No problem! Where my code abilities are limited, I try to help in other ways. Can't wait for v14, should make things easier on the code side for you, with regards to implementation of mobile responsiveness for v15. Again, best of luck.
