### ISSUE TITLE
Addition formular in a table

### ISSUE THREAD

**Issue by mwendwa5** [GibbonEdu/core#283]
Is it possible to have a formula in the tables you insert in expenses? Kinda like basic formulars in MS Word since already there are many formatting functions

![image](https://user-images.githubusercontent.com/4364019/27253679-8a5a69d0-5381-11e7-9dd3-9bebe6d050f0.png)

**Comment by rossdotparker** [comment]
Bruce, I'll answer this one in the forum. In future, please try and post only bugs here, and everything else in the forum. Double-posting slows us down, as I am sure you can understand. Thanks, Ross.
