### ISSUE TITLE
Future absence 

### ISSUE THREAD

**Issue by CafSentryGnome** [GibbonEdu/core#286]
After upgrading to v14 future absences are no longer showing up in attendance by roll group only in attendance by class.

**Comment by SKuipers** [comment]
Hi @CafSentryGnome 

Some settings were added to v14 to handle pre-filling attendance from other contexts, I think the default settings should be on for attendance by roll group, however you can check to be sure in School Admin > Attendance Settings, and look in the Pre-Fills & Defaults section.

**Comment by SKuipers** [comment]
Hi CafSentryGnome,

I believe this has been resolved so I'm closing this issue. Be sure to give a shout on the support forums if you have any further questions.

Thanks!
