### ISSUE TITLE
installer not finding '..\config.php' 

### ISSUE THREAD

**Issue by joanatam** [GibbonEdu/core#287]
Hello!  I'm unable to install the current stable build (github) using the installer.  I get the message:
"The directory containing the Gibbon files is not currently writable, or config.php already exists in the root folder and is not empty or is not writable, so the installer cannot proceed."  

I notice that config.php is in "../src/Gibbon" ... am I doing something wrong?

**Comment by joanatam** [comment]
Whoops.  I did "touch config.php" in the root folder, and the got past this error.
Now I'm trying to get past a new installer issue creating the DB: "Errors occurred in populating the database; empty your database, remove ../config.php and try again."  

I will close this issue, and log the DB creation issue, if I can't get past it.  THANKS

**Comment by joanatam** [comment]
Just needed to add 1 manual step before loading gibbon: "touch config.php; chmod a+w config.php".  Install continued after that.  Thanks.

**Comment by SKuipers** [comment]
Hi joanatam,

Sounds like your root directory may not be writable, or the process running PHP doesn't have enough permissions to access files in the root. Something like `chmod -R 755` usually helps, but you may need to also adjust the `chown`/`chgrp` to match the same user as your webserver (depending on your server setup).

The config.php file is created as part of the install process. If you're seeing the "Errors occurred in populating..." message you can re-set the install process by deleting the config.php file and emptying the database.

_Note: the config.php file in the root is not the same as the ./src/Gibbon/config.php (the files in /src are part of the core and shouldn't be changed)._

**Comment by joanatam** [comment]
Thanks for the fast reply!  I did discover that the config file in ./src/Gibbon/ was different, and the config.php in the root folder needed to be empty (hence the 'touch'), but the installer didn't create the file for me ... it did populate it, however, once I created an empty one, and we got past the verification in install.php.  

I did take your advice, ensuring the entire distro (root on...) is writeable, and changing owner to apache.  I'm still not able to get past the DB issue right now, but I'll certainly update you once I figure out what's up.  THANKS AGAIN!

**Comment by SKuipers** [comment]
Creating the empty config.php file may be what's confusing the installer (the presence of the file tells the system that is already installed, but if the database isn't populated you'll get an error message). Now that you've changed the root to writeable you should be able to delete your empty config.php file, empty your database (if it has any tables) and proceed with a fresh install.

Hope this helps! Be sure to check out the support forum too: https://ask.gibbonedu.org/  (there's always a chance similar issues already have a solution posted).

**Comment by crayner** [comment]
Hi Sandra,
On a linux box write is not the same as create, so the fact that it worked
after the creation of the empty config file may indicate, or the config
file was created by a different linux user, and the touch fixed the user
rights for the web server user.  All possibilities!

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Phone: +61 2 6352 5571
Mobile: +61 456 560 018

**Comment by joanatam** [comment]
Thanks for your notes, 'Skippers' and 'crayner'.

OK I see ... I thought  the php line that was tripping me up had it as:
if (is_writable('../config.php') == false) 
but on second look, I do see:
if (is_writable('../') == false) 

Thanks for solving that!

For the record, I'm testing the install on 2 platforms: 
(1) Codeanywhere IDE: Centos 6.5 w PhP 7 etc, and 
(2) Cloud9 IDE: Ubuntu 14.04 w PhP 5.5.9 etc ... 

it's only the former (Centos6.5 on Codeanywhere) that has been giving me problems.  I'm still stuck, not getting a clean DB init (with or without seeding data) on Platform #1 ... 

I think the message for tonight is that I'll move forward on the Ubuntu platform, and try to figure the out the Centos issues as time permits (it may involve trapping an exception thrown in  gibbon.sql?)

I'm past the User Setup in the Ubuntu cloud, so I think I'll continue on from there.

So far looks like some very fine work -- thank you for your contribution!

Thanks for your help -- I will check out the support forum, and follow up as appropriate!

**Comment by crayner** [comment]
Hi joanatam,
 Then the issue may be SeLinux on Centos 6.5.  If you have root access to
the terminal of that host, then temporarily disable selinux  and see if the
system installs correctly.  Should this be the case, then selinux need
​s to be altered ​
to allow create/write by the server to the appropriate directory.  This is
a complexed process that your System admin can work on.
​  (Codeanywhere staff?)


Details for Centos 6.5 and SeLinux can be found at
https://www.centos.org/docs/5/html/5.1/Deployment_Guide/sec-sel-enable-disable.html.


Please ensure that any changes you make to Selinux are restored, as this is
a key system for file security on your system.
​  ​

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Phone: +61 2 6352 5571
Mobile: +61 456 560 018

**Comment by joanatam** [comment]
OK thanks for your follow-up, crayner.  I just read another user's experience with Centos7:

https://ask.gibbonedu.org/discussion/1890/installation-on-centos-7

So it does seem I need to tweak the selinux settings prior to install if I want to run from there.  For now I'll continue to checkout the ubuntu install.  

Thanks Again!

**Comment by jzblbd** [comment]
Using OS: MacOS Mojave

Question: 
Where is this ../config.php located? In the linux box or on the Mac? If in Linux, what is the full path

I installed XAMPP and downloaded the Gibbon core v16.0.01. Was also able to: 
- start XAMPP with given address 192.168.64.3
- successfully started all 3 services ProFTPD, Apache, MySQL
- Network localhost:8080 -> 80 (Over SSH) enabled
- Network localhost:8443 -> 8443 (Over SSH) enabled
- Volumes /opt/lampp mounted
- create a folder /gibbon in 192.168.64.3/lampp/htdocs/gibbon (or in the linux box /opt/lampp/htdocs/gibbon)
- copy the files unzipped from Gibbon v16.0.01 and paste into ../gibbon folder above

But when I "Go to Application" which takes me to http://192.168.64.3/gibbon/installer/install.php, this error message came out - "The directory containing the Gibbon files is not currently writable, or config.php already exists in the root folder and is not empty or is not writable, so the installer cannot proceed."

I read the above and tried to chmod to the following directories:
- chmod 755 -R * (in the /opt/lampp and /opt/lampp/htdocs directories)
- find /opt/lampp/htdocs -type d -exec chmod 755 {} \;
- find /opt/lampp -type d -exec chmod 755 {} \;

Yet, the error still remains at http://192.168.64.3/gibbon/installer/install.php page.

Please could someone guide me through this process. Thank you.

**Comment by rossdotparker** [comment]
Hi jzblbd, you'll find config.php in your gibbon root folder, so that would be http://192.168.64.3/gibbon/ for you. The presence of this file is used as a flag that the system is installed, so when you first load Gibbon (prior to installation), the file is not there and it redirects to the installer. The installer creates this file using the database inputs you enter.

Do you see config.php in your Gibbon root? If not, then it is a permissions error (that would be my guess).

chmod 755 -R * will work if your user is the user that the web server uses to run (in Ubuntu this is www-data). You could try chmod 777 -R * and see if this resolves the problem: this is not a permanent fix, but would test whether or not permissions are indeed the issue here.

I hope this helps.

Ross

**Comment by markxus23** [comment]
Hi Ross I'm having the same issue but i'm running windows 10... my server is xampp can you guide me how to fix this issue

**Comment by jimbo8098** [comment]
@markxus23 This kind of error would, to me, suggest a permissions issue. I assume the config.php file is within the site root?

**Comment by markxus23** [comment]
Yes the config.php file is in the gibbon folder in my htdocs folder of xammp

**Comment by SKuipers** [comment]
Hi markxus23, this may be a file permission error. The answers above are for Linux systems, the best bet for windows 10 xampp would be to do some google searches to see how permissions are set. A quick search for "xampp file permissions windows" turned up the following article that may help: https://stackoverflow.com/questions/9349469/changing-php-write-permissions-in-xampp-on-windows-7

**Comment by markxus23** [comment]
Thanks a lot. I'll try to see if i can search that. Thanks a lot. For now
i'll see what i can do. Thanks again
