### ISSUE TITLE
Application Form submit error when not select family name by logged in user with family.

### ISSUE THREAD

**Issue by hanattaw** [GibbonEdu/core#291]
The error shown "Your request failed because your inputs were invalid."

I've fixed this by manually select family name.

<img width="766" alt="screen shot 2560-08-05 at 14 44 47" src="https://user-images.githubusercontent.com/3141235/28993961-ab15048c-79ec-11e7-8914-dd06bda4df2a.png">

After searching in the code i see the "addRadio->checked($checked)" the checked method need to give the value but not not boolean.

**Comment by SKuipers** [comment]
Thanks! Good catch, just PR'd a fix. Sounds like you're familiar with PHP, if you'd like to pull request any fixes for bugs you find feel free to give a shout with any dev questions 😃

**Comment by rossdotparker** [comment]
@hanattaw good catch indeed, and thanks for pointing out the solution. Let me know if you want to be added to the team here on GitHub so you can put in pull requests yourself. And, you are welcome to join us on Slack (just let me know and I will invite you) where we do our dev chat.

This issue has been merged into v15 dev branch in commit https://github.com/GibbonEdu/core/commit/a7cd7f03ec097b32d4ecb1f1b1b364c0cb3b7ccc. Feel free to test and feedback. In the meantime I will close this ticket.

**Comment by hanattaw** [comment]
@rossdotparker Thank you. Please add me to the team.

**Comment by rossdotparker** [comment]
Done!
