### ISSUE TITLE
School Closed Error

### ISSUE THREAD

**Issue by mictsao** [GibbonEdu/core#30]
After clicking the "Space Booking" checkbox under the timetable, the year fast forwards to a date in the future. This would repeat until it reaches January 1, 2024.

The schedule would also indicate that the school is closed. Even going back to the original date will results in a schedule that shows the school is closed. 

Screenshots have been attached.
![screen shot 2015-06-30 at 1 15 06 pm](https://cloud.githubusercontent.com/assets/12396848/8440893/10e458be-1f2a-11e5-8f1f-52fa363de2e8.png)
![screen shot 2015-06-30 at 1 15 15 pm](https://cloud.githubusercontent.com/assets/12396848/8440892/10da9a54-1f2a-11e5-963b-0e5c919b2b06.png)

**Comment by rossdotparker** [comment]
mictsao, thanks for posting this issue. The timetable only shows data from within the current school year, so scrolling into the future with always show this issue. To see the timetable in future years, please log out and log into another year (using the Options link on the login form). Hope this helps: if not, let me know. Ross

**Comment by mictsao** [comment]
Hi Ross, thanks for getting back to me so quickly. The curious thing is that I didn't scroll to any dates. The system skips to a random future date when I check, "Space Booking", so the system involuntarily moves me to a future date. For example, after checking the "Space Booking" box, the date will now show 1 year into the future. 

Your system is incredibly robust, and we've really enjoyed trying out the latest release. Great job!

Michael (michael.t@examguardian.com)

**Comment by rossdotparker** [comment]
Michael, thanks for this. The video was vital in working out the issue, as it is US-date specific, and so we would never have found it as we use UK-style dates. It has now been fixed for v11, and the fix should be backwards compatible to v10. To patch your version, get /modules/Timetable/moduleFunctions.php from the commit linked below, and upload it to your install:

https://github.com/GibbonEdu/core/commit/4768fc8852ac1e9d337a77ea4a10acc8986d0ec3

Let us know if this does the trick.

Thanks,

Ross

**Comment by mictsao** [comment]
We successfully deployed the patch. This took care of the issue perfectly. Thank you Ross. 
Michael
