### ISSUE TITLE
Display the application form in two languages

### ISSUE THREAD

**Issue by myii** [GibbonEdu/core#31]
International school setting in Saudi Arabia, wanted to know if the application form could be displayed in both English and Arabic at the same time.

I've put together a wrapper function for `gettext` that provides this functionality, for any choice of second language.  If no second language is desired, shows the application form as usual.

Some images to give an idea of how it looks:

![screenshot1](https://cloud.githubusercontent.com/assets/10231489/8510250/3a63d546-22d3-11e5-9ba2-31713fa93a76.png)
![screenshot2](https://cloud.githubusercontent.com/assets/10231489/8510251/3a64a41c-22d3-11e5-9240-965f5f79e92e.png)
![screenshot3](https://cloud.githubusercontent.com/assets/10231489/8510252/3a6e82c0-22d3-11e5-9936-1e733c6e7554.png)
![screenshot4](https://cloud.githubusercontent.com/assets/10231489/8510254/3a73000c-22d3-11e5-88dd-a151d980ce38.png)
![screenshot5](https://cloud.githubusercontent.com/assets/10231489/8510253/3a71d434-22d3-11e5-8b93-7523f2fd7fef.png)
![screenshot6](https://cloud.githubusercontent.com/assets/10231489/8510259/c59bdf78-22d3-11e5-8991-cbae256ae407.png)

As can be seen in the final image, this is not limited to having English as the primary language.

Do you have an interest in this functionality?  If so, how would you like me to share it?

**Comment by rossdotparker** [comment]
myii, thanks so much: this looks great. Can you push the code to the v11 branch so I can take a look? Does the second language have to be hard coded? Hopefully not, but if so, maybe we can code things so it can be specified as a database option. Thanks for your continuing contributions ; )

**Comment by myii** [comment]
@rossdotparker See you in the PR - hope you enjoy it!
