### ISSUE TITLE
Error in Multi TimeTable feature

### ISSUE THREAD

**Issue by everkool82** [GibbonEdu/core#33]
Hello Gibbon Team - I extend heartfelt compliments for the meticulous work done with Gibbon as a flexible school management system. However, I am reporting a issue here.

Version: 10.0.0.0
Role: Administrator
Platform - XAMPP for Windows

While exploring the multi timetable feature  offered in Gibbon (v 10.0.0.0), I came across an unexpected outcome for a routine scenario. At a high level,as an administrator, I was trying to set up two different timetables  for Junior Students (Year Group 7,8,9) and Senior Students (10,11,12,13).

After successful completion of required steps, I see two options for selecting timetable on my homepage (expected). However,  both show the same time table (unexpected). Whichever timetable was FIRST tied to date always shows up as the timetable for other one too. 

Please refer the attached screenshot with inline comments.  Kindly acknowledge.
Oops..unable to upload the .doc/.docx  - please follow this link to access the document:
http://bit.ly/1IguAwn

**Comment by rossdotparker** [comment]
everkool82, 

Thanks for sharing this bug, and for your very detailed description. I have replicated the issue, and it believe I have managed to fix it. It seems it was only occurring on the homepage, not when you viewed in the Timetable module.

The fix will be included in v11, but I am sure you will want it in your system in v10. The two files that have been edited (/index.php and /index_tt_ajax.php) in the commit linked below should be backwards compatible, so you can upload them into your v10 install.

https://github.com/GibbonEdu/core/commit/d5ad0feddfebac211089dcfe63ef2eb524be5040

Let me know if this works for you or not.

Ross

**Comment by everkool82** [comment]
That was a speedy response, Ross! 

On replacing the local files with the ones shared in the link above, the result did not meet the expectation. Home screen continued to show the timetable as before, plus string "here" is also reflecting.

Also, click on different timetables is yielding-  here'<'gibbonTTID'>'

Result Snapshot:
http://bit.ly/1TQuIXn

Steps followed:
Step1:
2 files - /index.php and /index_tt_ajax.php were copied from the github link (as shared above) into the local system in the corresponding directory.

Step2:
apache was restarted.

Anything, I am missing out ?

**Comment by rossdotparker** [comment]
We try to respond fast to help schools get the best out of Gibbon. The debug code you spotted was accidentally left in place after the fix went it, and has been fixed in this commi:

https://raw.githubusercontent.com/GibbonEdu/core/293894919fbef7a216fd188a5a8758286b593eea/index_tt_ajax.php

Beyond that, I have tested it, and can switch between timetables fine on the homepage now. Both showing as they should. Can you upload the fixed file and see if it makes a difference?

Does timetable switching work when you view a timetable in Learn > Timetable?

Thanks,

Ross
