### ISSUE TITLE
Markbook Audio Recording

### ISSUE THREAD

**Issue by recurza** [GibbonEdu/core#34]
Hi Ross,

I'm still stuck on this. When I record into a blob, I don't know how to send it along with the rest of the form when the user presses submit. I've tried xhr and form.append (but I might not be using it correctly).  
What other methods are there?

Thanks,

Steph

**Comment by rossdotparker** [comment]
Steph, don't store the blob in the database, as it will get too big. Try
setting the enctype on the form to allow file uploads. Check the markbook
data page to see how it works. Ross.

**Comment by recurza** [comment]
I see, so I should use a hidden file input and set the value to blob? And then upload it to the uploads folder?

**Comment by recurza** [comment]
Now I'm stuck on the uploading part. I can pass the blob by using $_POST, but I can't convert it to a wav file. It gives me a file with only 13 bytes.
I'm using `file_put_contents($path . "/" . $attachment, $_POST['rec']))`.

**Comment by rossdotparker** [comment]
Hmmm, what is the form of the blob in the first place? Is there a config
option in the recording library to get a file in a specific file?

WAV would be a terrible file format as well, as the files are huge...HUGE!
MP3 would be better, but there might be licensing issues.

Does this help? Keep digging ; )

On Sat, Aug 1, 2015 at 7:37 PM, Steph Ng <notifications@github.com> wrote:

> Now I'm stuck on the uploading part. I can pass the blob by using $_POST,
> but I can't convert it to a wav file. It gives me a file with only 13 bytes.
> I'm using file_put_contents($path . "/" . $attachment, $_POST['rec'])).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/issues/34#issuecomment-126890769>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by recurza** [comment]
Yep, I set the "mime type" to wav. But I'll have to find some way to
compress the wav to mp3
​, which means (I think) I still have to send the blob from the form to
add_process.​
