### ISSUE TITLE
Feature request: new status "Partly Paid" for invoices

### ISSUE THREAD

**Issue by Akuukis** [GibbonEdu/core#38]
Aim: To see unpaid invoices more obviously. 

It is already possible to pay partly but in that case invoice gets status of "Paid" thus making it impossible to filter them separately. And it is not convenient to filter by "Issued", then "Issued: Overdue" and then manually go through "Paid" invoices.

Suggestion: Add new status for invoices "Partly Paid" and add new filter condition that technically would be "Issued OR Issued: overdue OR Partly paid" called "Unpaid". I suspect that some extra edits in invoice editing view is also needed, for example force "Paid" to be paid fully, and extra conditions for changing the status.

I think I could do this myself, but then please someone point to the places of interest. Maybe better ideas how to accomplish this?

**Comment by rossdotparker** [comment]
Akuukis,

Thanks for this request. This item is actually already in the v11 Todo list (Item 37 at https://docs.google.com/spreadsheets/d/1v-5KnzbGxr9IyRdY_miq3jbSJx_UD5zZZujMkZXWdew/edit). Although that request is not 100% what you are asking for, the solution should meet your needs. 

I am just sitting down to work on this now, and will update the forum post that this request stemmed from once done, so keep an eye on this URL:

https://ask.gibbonedu.org/discussion/401/auto-calculate-paid-amount-total-invoice-amount-balance-amount

Thanks,

Ross
