### ISSUE TITLE
Feature request: summary of invoices for invoice view

### ISSUE THREAD

**Issue by Akuukis** [GibbonEdu/core#39]
Aim: To get overview fast

Example: if filtered by "Paid" in specific billing schedule, to fast understand how much money inflow was in that billing schedule.

Suggestion: edit the "X invoices in currect view" line to include also information as "Sum of Total" and "Sum of Paid", or make a new summary row beneath the results to present this information.

I think I could do this myself, but then please someone point to the places of interest. Maybe better ideas how to accomplish this?

**Comment by rossdotparker** [comment]
Akuukis, our resources are currently stretched getting ready for v11. If you would like to code and contribute this, you could look at the file /modules/Finance/invoices_manage.php. You could work on a fork of the v11 branch (https://github.com/GibbonEdu/core/tree/v11.0.00) and then push when you have it working.

Alternatively, you could look at setting up a custom SQL query in the Query Builder (https://gibbonedu.org/extend/) module to do this for you. I think it should be possible in SQL.
