### ISSUE TITLE
Composer based archtechure

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#462]
For long term maintenance, have you ever consider to restructure Gibbon into a [composer](https://getcomposer.org/) based project? Since you've already been doing namespace autoloading, it should be easy to do [PSR-4 autoloading](https://www.php-fig.org/psr/psr-4/). Then you can better reuse libraries available on [Packagist](https://packagist.org/) in the future.

**Comment by rossdotparker** [comment]
Hi yookoala, thanks for taking the time to stop by and chat. If you look at the code in the v16 branch you will see that we are making some moves in this direction. Our aim is that devs won't need to use composer in most cases, but the core team will make some use of it behind the scenes in order to manage packages. @SKuipers can tell you more, and she's leading the refactoring work we have going on to try and modernise the codebase. Cheers, Ross.

**Comment by yookoala** [comment]
It is a practical approach to have composer manage all the dependencies, then have a CI platform (e.g. Travis) to build a bundle for release. That way, you do not have to include the vendor folder into your repository.

I'd also suggest to use composer to handle modules installation, if possible.

**Comment by yookoala** [comment]
As to modernize the code base, I can see a big chunk of work in separating HTML output from business logic.

You probably should extract all business logic from the root folder's scripts. Reorganize them with routers like [fastroute](https://github.com/nikic/FastRoute) and some controller classes. Then rewrite the HTML view code with template engine like [Twig](https://twig.symfony.com/).

After a clean separation like this, you can have more flexibility for theming (e.g. have responsive theme with [bootstrap](https://getbootstrap.com/)).

**Comment by yookoala** [comment]
Sorry for length soup of verbose comments. Didn't mean to be rude.

Its nice to see HK based open source project. Stumbled upon this project by accident. I just wish this project well. I might as well send some PR to v16 if you don't mind :-)

**Comment by crayner** [comment]
Ah, memories

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Phone: +61 2 6352 5571
Mobile: +61 456 560 018

**Comment by rossdotparker** [comment]
Thanks for all the input yookoala. Your thinking is more or less aligned with the direction in which we are heading. It is just taking a lot of time to refactor a large, legacy codebase in a way that is not disruptive to the schools that already depend on Gibbon. In v15 we wrapped up an OO rewrite of almost all interface forms. In v16 we are finishing that work, moving on to data tables and also some back end  OO work. We will then look into, as you say, separating out more of the business logic. One step at a time. Any PRs are appreciated, particularly if they tie in with the work we already have going on.
