### ISSUE TITLE
Parent Module

### ISSUE THREAD

**Issue by syzuhdi** [GibbonEdu/core#480]
Hi,
Does GibbonEdu has a module for Parent such as to view their childs grade?

Regards.

**Comment by SKuipers** [comment]
Hi @syzuhdi 

Yes, Gibbon has a parent dashboard where parents can see markbook grades, attendance, lesson plans, etc depending on the settings and permissions that have been enabled by the school admins. See the docs for more info: https://docs.gibbonedu.org/parents/  (the screenshots are a bit out of date but the gist is there).

Hope this helps!

**Comment by syzuhdi** [comment]
Thank you @SKuipers
