### ISSUE TITLE
CSV user import MIMETYPE error

### ISSUE THREAD

**Issue by SKuipers** [GibbonEdu/core#49]
Hi Ross & Gibbon Developers,

When importing a CSV file of users by following the instructions, using the sample file and using LibreOffice, I continue to get the following error:

"Import cannot proceed, as the submitted file has a MIME-TYPE of application/csv, and as such does not appear to be a CSV file."

Version: 10.0.0.0 (also found in v11.0.00dev)
Role: Administrator
Platform - LAMP (& MAMP Localhost for v11)

It seems to me that application/csv should be a valid MIMETYPE for CSV ;)  This is what LibreOffice is exporting "Text CSV (.csv)" as.

I was able to fix the issue for myself by editing line 201 of modules/User Admin/import_users.php and adding ($_FILES['file']['type']!="application/csv") to the IF statement. After that the import succeeded. 

Obviously editing the core isn't a recommended solution, so I'm passing along the bug report to you.

Thanks!

![screen shot 2016-01-20 at 9 50 58 am](https://cloud.githubusercontent.com/assets/897700/12437737/602c914e-bf5b-11e5-9dcc-a3b4c9deebd1.png)

**Comment by rossdotparker** [comment]
Sandra,

Thanks for this. I have applied your fix to all spots in Gibbon where CSVs are imported. Oddly, my LibreOffice seems to be using one of the MIME types in the original list, and so is behaving differently to yours. You can check out the changes in the following commit:

https://github.com/GibbonEdu/core/commit/8c596075cf45dd078ff55765d444b3f9d7a67270

Appreciate your input on this one : )

Ross
