### ISSUE TITLE
User Admin - Import families failing 

### ISSUE THREAD

**Issue by aisachiu** [GibbonEdu/core#50]
Getting fails for importing family, even though (I think) my data files seem like requested.

Wondering if there is an issue with import_families.php

After a quick look into User Admin**/import_families.php**, the SQL statements don't seem to match the **gibbonFamily** table field names on lines 414 and 439 (update and add family). Looks like gibbonFamily has been changed with field "languageHome" (in the php) now becoming 2 fields "languageHomePrimary" and "languageHomeSecondary"

However, rewriting the line 439 to 

 `$sql="INSERT INTO gibbonFamily SET name=:name, nameAddress=:nameAddress, homeAddress=:homeAddress, homeAddressDistrict=:homeAddressDistrict, homeAddressCountry=:homeAddressCountry, status=:status, languageHomePrimary=:languageHome, familySync=:familySync" ;`

still didn't work (even though I allowed NULLs for languageHomeSecondary in the tables)

![aisgibbon1_-_ais_gibbon_-_user_admin_and_downloads](https://cloud.githubusercontent.com/assets/9045310/13146172/675daee4-d68f-11e5-8b1a-73e6c8962677.gif)

**Comment by rossdotparker** [comment]
This has been fixed in https://github.com/GibbonEdu/core/commit/b7cca3d2073d136ff9072ccd3658c3d38d10e9f6. Thanks for reporting the bug.
