### ISSUE TITLE
Error in function isFileValidType

### ISSUE THREAD

**Issue by camachogfelipe** [GibbonEdu/core#503]
## Expected Behavior

When system valid a File Type extension, return true

## Actual Behavior

When system valid a File Type extension, return false always

## Steps to Reproduce

1. Edit user
2. Select image user
3. Send form
4. Return image don't upload

## Your Environment

* Gibbon Version: 15.0.00
* Browser Name and version: All

The error was solved by changing line 323 to the following:
$extension = mb_substr(mb_strrchr(strtolower($filename), '.'), 1);

**Comment by SKuipers** [comment]
Hi Felipe. I've checked out the line you've mentioned and in v15 and earlier it appears to be the same as the code you've provided `$extension = mb_substr(mb_strrchr(strtolower($filename), '.'), 1);`

I wonder if this is maybe related to a similar issue that was fixed for v16: https://ask.gibbonedu.org/discussion/comment/4034#Comment_4034 Are there perhaps any `.` in your usernames? If so, please do try the fix linked to from that post and let us know if it helps.

Thanks!
