### ISSUE TITLE
Website - Correction

### ISSUE THREAD

**Issue by onaforeignshore** [GibbonEdu/core#610]
On [this page](https://docs.gibbonedu.org/administrators/getting-started/installing-gibbon/google-oauth/), there is an "s" missing in the URL - intall vs install:

> 9. In the new client ID window, do the following:

> Choose Web Application.
> Set Authorised Javascript origins to the url of gibbon on your server.
> Set Authorised Redirect URI to http://www.your-gibbon-intall/lib/google/index.php. The googleOAuth folder is in the in the lib folder of Gibbon v14.0.00 and above on your server.

**Comment by SKuipers** [comment]
Hi Christo,

Awesome, thanks for the corrections! The docs are open source, any interest in submitting the changes through GitHub? There's an edit link in the [top-right of each page](https://github.com/GibbonEdu/docs/edit/master/content/administrators/getting-started/installing-gibbon/authenticating-with-google-oauth.md) Each page can be edited in markdown and submitted as a GitHub pull-request.

Thanks!

**Comment by SKuipers** [comment]
Awesome, thanks! All PRs merged.

**Comment by SKuipers** [comment]
Thanks again! Feel free to submit any other corrections you come across :)
