### ISSUE TITLE
Variables $themeCJS declared and not used.

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#615]
There are only 2 occurrence of a the variable `$themeCJS`:
* [fullscreen.php](https://github.com/GibbonEdu/core/blob/ca259435be1a8de70d7340b9f643315122f4e819/fullscreen.php#L70)
* [report.php](https://github.com/GibbonEdu/core/blob/ca259435be1a8de70d7340b9f643315122f4e819/report.php#L67)

Are they obsoleted? Are they supposed to be `echo` after `$themeJS`? Or are they typo of `$themeJS`?

## Your Environment
* Gibbon Version: 16.0.00
* Browser Name and version:

**Comment by SKuipers** [comment]
Thanks for the fix! PR is merged 👍
