### ISSUE TITLE
Poor debug message when error occurs

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#670]
If you're a developer who wants to help this project, eventually you'd encounter some error. And right now, you'll only be seeing this:

![2018-10-26 11-26-50](https://user-images.githubusercontent.com/91274/47542892-18972f00-d912-11e8-963d-0dd53b180bdd.png)

You'll have hard time getting the error stacktrace. And that is a painful process.

PHP frameworks like Slim, Laravel and CakePHP usually offer a better error page when in debug mode. With the help of library like [flip/whoops](https://github.com/filp/whoops), developer get to have better insights to debug in the error page like this:

![Whoops example screen](https://camo.githubusercontent.com/31a4e1410e740fd0ccda128cbcab8723f45e7e73/687474703a2f2f692e696d6775722e636f6d2f305651706539362e706e67)

With better understanding to the bug encountered, developers in the community can tackle the problem much easier and thus better contribute to the project.

## Your Environment
* Gibbon Version: v17.0.00 development version (e51e4a64)
* Browser Name and version: Doesn't matter

**Comment by SKuipers** [comment]
Hi Koala,

We recently tackled some of the error handling in Gibbon v17. I think perhaps check your System Settings to ensure it's set to Development or Testing. Also, your php.ini should have `error_reporting` enabled, ideally with `E_ALL`, and `display_errors 1`. It's not quire as full-featured as a third-party library, but it's lightweignt and certainly has stack traces. 

Hope this helps! Feel free to make use of the #core_development chat on slack too 😃
