### ISSUE TITLE
Composer based library management

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#691]
**Refactor**

## Description

This issue is supposed to be for tracking a few upcoming PRs that aims to solve the same problem.

Composer provides easier to track version control and locking mechanism for modern PHP libraries. It also come with an automatically generated autoloader for any OOP style libraries. It encourage and assist the use of PSR-4 compliant libraries. Switching to autoloader based library calls remove the problem with library path discovery and a whole class of problem.

* Every PHP library that can be managed by composer should be.
* Every PHP class that can be autoloaded by composer autoloader should be.

## Motivation and Context

* To simplify the external library management in long run.
* To make it easier to upgrade to different version of the same library in the future.

## Libraries to Migrate

* [x] PHPMailer
* [x] PHPExcel
* [x] Google API Client
* [x] TCPDF

## PHP in the "/lib" Folder That We Won't Touch Yet

* `/lib/google/index.php`
  A Gibbon custom script written with Google API Client. Not part of the API Client library itself. Will not touch this until we have a good solution for controller / routing for such case.
* `/lib/paypal/*.php`
  Custom written script for payment. Should rewrite this completely with official PayPal client library or other payment library available in Packagist.

**Comment by SKuipers** [comment]
Just merged the last of these changes into the core 🎉 Thanks!!
