### ISSUE TITLE
PHP Fatal error:  Call to a member function prepare() on a non-object in \functions.php on line 3004

### ISSUE THREAD

**Issue by vishal001** [GibbonEdu/core#7]
Hi Ross,

I am trying to integrate module in my hosting server. But getting this error.
Please help and correct me how to integrate and upload it on server.

What other setting i need to change.

Thanks

**Comment by rossdotparker** [comment]
Vishal001, thanks for trying Gibbon! This is not a problem we have seen before. Are you using the current, stable version 9.0.00? What kind of server are you on, can you give me some more details? What page is this happening on? The installer? I am wondering if your host supports PDO database library in PHP, which is essential for Gibbon.

**Comment by vishal001** [comment]
I am using godaddy hosting site. It is happening on index.php page.

**Comment by rossdotparker** [comment]
Vishal, did you install yourself? I think GoDaddy includes Softaculous in CPanel, which allows you install with no fuss. Either that, or try and upload all files again from a fresh download, in case something went wrong with the download or upload.

**Comment by vishal001** [comment]
Thanks, Please can you give me download link which you think will have no issues?

**Comment by rossdotparker** [comment]
Try: https://gibbonedu.org/download, which uses the GitHub download, but gives you the latest stable version. In future, please post questions to http://forum.gibbonedu.org, rather than GitHub, which is aim more for our developers. Thanks! Good luck, let me know how you get on.

**Comment by vishal001** [comment]
Hi Ross,

PHP Fatal error:  Call to a member function prepare() on a non-object in \core-9.0.00\functions.php on line 3004

same error when i am uploading website to godaddy hosting site.
Please help.

Thanks

**Comment by dickybagus** [comment]
Please don't reply from here, I will help you,  contact me on dicky.bagus@gmail.com. Thank you 
--
Sent from myMail app for Android
Saturday, 14 February 2015, 08:41PM +07:00 from vishal001 <notifications@github.com>:
vishal001 (notifications@github.com) is not on  your Guest List |  Approve sender |  Approve domain
Hi Ross,
PHP Fatal error:  Call to a member function prepare() on a non-object in \core-9.0.00\functions.php on line 3004
same error when i am uploading website to godaddy hosting site.
Please help.
Thanks

**Comment by vishal001** [comment]
Do I need to update any setting or change server settings?
Do we need config.php?

**Comment by rossdotparker** [comment]
Dicky, thanks for your offer of help!

Vishal, please email Dicky, and I am sure he will be able to help you. config.php is created by the installer, which should run on first access to the site. In terms of server settings, etc, check out the details at the top and bottom of https://gibbonedu.org/support/administrators/installing-gibbon/

**Comment by vishal001** [comment]
I have started to contact dicky. Looking for his help. 
Many thanks, Ross, Dicky,

**Comment by vishal001** [comment]
Thanks Dicky, with your help I can move on.

Many Thanks.
