### ISSUE TITLE
"First Aider" showing current user name when editing

### ISSUE THREAD

**Issue by jian118** [GibbonEdu/core#765]
When editing first aid record, the "First Aider" shows logged in user instead of recorded data

## Expected Behavior
First Aider should show who provided the first aid

## Actual Behavior
First Aider now showing logged in user

## Steps to Reproduce
1.People
2.First Aid
3.Under first aid records, press the edit button

## Your Environment
* Gibbon Version: v16.0.01
* Browser Name and version: Chrome

**Comment by SKuipers** [comment]
Thanks @jian118, well caught! I've created a fix for v17 (releasing Jan 20, 2019), but the change can be incorporated back into v16 if needed, just make the same highlighted change to the code in `firstAidRecord_edit.php` from this commit: https://github.com/GibbonEdu/core/commit/2ea7c8e26f935d2f051f4660424ecffea5939f5f

**Comment by SKuipers** [comment]
This bug has been fixed in the upcoming v17, so I'm closing the issue. Be sure to let us know if you spot anything else, thanks!
