### ISSUE TITLE
Student Extra Homework

### ISSUE THREAD

**Issue by hanattaw** [GibbonEdu/core#767]
How can a teacher see the extra homework those student submitted? 

When student did online submission and included with extra homework, How teacher see the extra homework for particular student?

_Student submitted file with extra homework._
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3141235/50645302-d2abb680-0fa5-11e9-8e26-8cca6487d2db.png">

_Teacher see online submission_
<img width="400" alt="screen shot 2562-01-03 at 22 21 32" src="https://user-images.githubusercontent.com/3141235/50645407-11da0780-0fa6-11e9-8471-72aebe32f954.png">

_This link has not go to see extra homework_
<img width="400" alt="screen shot 2562-01-03 at 22 23 28" src="https://user-images.githubusercontent.com/3141235/50645497-48178700-0fa6-11e9-8fe1-d0230caa7546.png">

## Expected Behavior

The teacher should see extra homework on the View Lesson Plan page, if any student submitted extra homework Plan.

## Actual Behavior

Teacher can not see any extra homework that student submitted. Best thing teacher can see is go to view student profile with homework subpage. But unfortunately that link go to View Lesson page with out see any extra homework.

## Steps to Reproduce

1. Student did online submission with enter extra homework.
2. Teacher view submitted homework on View Lesson Plan.
3. Teacher only see file/link attached. No extra homework link show.

## Your Environment

* Gibbon Version: 16.0.01
* Browser Name and version: Safari Version 12.0.3 Mac OS , Chrome Version 71.0.3578.98 (Official Build) (64-bit) Mac OS

**Comment by rossdotparker** [comment]
Hi @hanattaw this is a good question. As you have seen, there are two ways to record homework (e.g. to make a note that homework has been assigned):

1. The teacher records the homework for all students (some teachers prefer this as it is more efficient)
2. The teacher asks students to record the homework for themselves (some teachers prefer this as it places responsibility on the student)

Only the first approach allows submission of homework to Gibbon. If students record their own homework, there is no field for them to submit it.

Does this answer your question?

Ross
