### ISSUE TITLE
v17 Date Picker Inconsistency

### ISSUE THREAD

**Issue by robacarr** [GibbonEdu/core#769]
I am demoing Gibbon 17.  The date picker format and required format for the Term creation form do not match.  en_us is the default language for my installation.  This appears to be similar to (but opposite of) the issue reported in #348.

## Expected Behavior
It should fill in the date in format mm/dd/yyyy

## Actual Behavior
Calendar widget fills in date as dd/mm/yyyy

## Steps to Reproduce
![calendar date picker gibbon 17 0 00](https://user-images.githubusercontent.com/46637715/51080381-67966a00-16a0-11e9-87aa-8a8b623035cb.png)

1.  Navigate to this form:   Home > School Admin > Manage Terms > Add Term
2.  Fill in the dates for First Day or Last Day
3.  Note that the date fills in as dd/mm/yyyy whereas the validation expects mm/dd/yyyy.

## Your Environment

* Gibbon Version: 17.0.00
* Browser Name and version:  Safari 12.0.2

**Comment by crayner** [comment]
Hi robacarr,
Had a look at this issue for you and have found the cause, being the lack of the Gibbon implementation of DatePicker to correctly format the date for en-US as the correct definition file for en-US is not required as it is the default for datepicker, but the default for Gibbon is en-GB, the true form of English. (Sorry, could not help myself.)   I have created a pull request for this repair at https://github.com/GibbonEdu/core/pull/770

**Comment by robacarr** [comment]
Wow Craig, that was fast!  I'll keep an eye on the pull request and act accordingly.  

Thanks for trying to help accommodate those of us who speak Western slang.

Rob

**Comment by SKuipers** [comment]
Hi Rob,

I've merged this in. Luckily there is only one file changed for this fix, so if you update your `index.php` to match the version now in v17 you should see the datepicker working correctly. https://github.com/GibbonEdu/core/pull/770/files

Thanks!

**Comment by robacarr** [comment]
Again, what speed!

I have incorporated the update into my local install and have confirmed desired behavior.  

![pasted graphic 4](https://user-images.githubusercontent.com/46637715/51093276-a93e1800-1767-11e9-9421-5031c4dc9270.png)

Thank you both!

Rob
