### ISSUE TITLE
Markbook column title showing term's name when term filtering is applied

### ISSUE THREAD

**Issue by jian118** [GibbonEdu/core#782]
In Markbook page, if term is selected, the title of each markbook column is showing Term name instead of the markbook column name. 

Simple Fix:
In src\Domain\Markbook\MarkbookColumnGateway.php Line 47 change to the following
`->cols(['*','gibbonMarkbookColumn.name as name'])`

Problem seems to be caused by the same `name` used in the database for gibbonSchoolYearTerm and gibbonMarkbookColumn where the column gibbonSchoolYearTerm name overwritten the `name` field

**Comment by SKuipers** [comment]
Aha, well caught! Missed that one during testing 😅  I've applied your fix to the v18 branch: https://github.com/GibbonEdu/core/commit/0677534dd1d018c4065bc625a24097d3eb5e2111

Thanks @jian118!
