### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lAlejo** [GibbonEdu/core#784]
Hello, I just downloaded the last gibbon update from the oficial site. I uploaded all the files to my server and when I try to run the wizard I get this error.

Parse error: syntax error, unexpected '?' in /src/Services/CoreServiceProvider.php on line 174

**Comment by SKuipers** [comment]
Hi @lAlejo I'm closing this issue, in hopes that you've found a solution by now. If not be sure to check out our support forums at https://ask.gibbonedu.org

**Comment by lAlejo** [comment]
Hello. Thanks.

I found the solution. It was the PHP version.

Sorry for not notify.
--
[image: Facebook] <https://www.facebook.com/techingrd/>
[image: Instagram] <https://www.instagram.com/techingrd/>
[image: Telegram] <https://t.me/lorenzoalejo>
[image: E-Mail] <lorenzo.alejo@gmail.com>
[image: Web Site] <https://do.linkedin.com/in/lorenzoalejo>

Lorenzo Alejo
Teching RD
(829) 546 4250
[image: La imagen puede contener: texto]

**Comment by itcdsc** [comment]
I have the same issue. I'm running PHP72 but the error still persists while installation.

**Comment by rossdotparker** [comment]
@itcdsc how are you checking your PHP version? If you check on the command line, you sometimes get a different version than that being used by your web server. Are you able to use phpinfo() to confirm the webserver's version of PHP? Thanks!
