### ISSUE TITLE
Empty translation string in source code

### ISSUE THREAD

**Issue by yookoala** [GibbonEdu/core#802]
**Describe the bug**

Scanning source code with `xgettext`. Found translation function call `__()` with empty string `""` as input. This should not happen. Calling `gettext("")` will return the header information of a PO file, which might be unexpected for the use case.

Location:
[Line 149, `modules/User Admin/applicationFormSettings.php`](https://github.com/GibbonEdu/core/blob/467f5099330825af47e2ab9791d484d3b8c5139b/modules/User%20Admin/applicationFormSettings.php#L149)

**To Reproduce**
* Simply open the source file `modules/User Admin/applicationFormSettings.php`.

**Expected behavior**
All translation msgid should be something other than empty string.

**Comment by SKuipers** [comment]
Aha, well caught! I've pushed a fix: https://github.com/GibbonEdu/core/commit/29eb13fc718aff0d1bbb244ad3d7be241fa9bb59
