### ISSUE TITLE
A case for Tailwind CSS

### ISSUE THREAD

**Issue by SKuipers** [GibbonEdu/core#805]
Hi folks!

As we work towards a goal of responsive design in Gibbon, I’m increasingly leaning towards Tailwind over Bootstrap for our chosen css framework.

Personally I’ve used Bootstrap, Foundation and Tailwind for several past projects, and lately find myself consistently choosing Tailwind for new projects. Beyond just personal preference, I’ve put together some thoughts here to share why I think it’s a good fit for Gibbon.

### What is Tailwind?

Lots of people are likely to be familiar with [Bootstrap](https://getbootstrap.com/), so if you haven’t heard of Tailwind I’d encourage you to check it out: [Tailwind CSS - A Utility-First CSS Framework for Rapid UI Development](https://tailwindcss.com/docs/what-is-tailwind/)

I was in the semantic css camp for years! Making the mental shift to utility classes does take some getting used to, but it really starts to click once you’ve used it in practice. The following article was the tipping-point for me, and has the most comprehensive argument for utility-based css I’ve come across: [CSS Utility Classes and "Separation of Concerns”](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/)

### Why is Tailwind a good fit for Gibbon?

**Design Freedom** - Bootstrap is great in that it provides a kitchen sink of useful components. For a blank-slate project, this helps get developers up to speed with less style decisions. In Gibbon’s case, it already has particular a visual identity and existing components: by adding Bootstrap, we would both be inheriting a number of pre-defined components, and fighting with conflicts in the ones we already have.

Tailwind on the other hand doesn’t impose design decisions on the pre-existing css. We could work to incrementally replace existing classes with either utility classes or component-based css as needed, without breaking the current layouts and styles.

**Javascript Agnostic** - Bootstrap is both a css and javascript framework, based on jQuery, which is increasingly outdated in respect to modern javascript. Tailwind is purely css, giving us the freedom to choose a javascript solution that would best fit the project: Vue, React, Web Components, etc.

**Easily Composable** - Gibbon has a lot of functionality that’s specific to it’s needs: markbooks, timetabling, attendance, rubrics, etc. These aren’t covered in a kitchen-sink framework, so with any chosen option we would still need to create these. With the utility-based approach, developers already have a toolkit of classes they can use to compose new components that are cohesive within the overall UI design system.

**Rapid Development** - There’s inline style throughout Gibbon (which we’re refactoring out!), but part of the reason they’re there in the first place is that semantic css can often be tedious: in lots of cases you just need to align some text and nudge a layout by a few pixels, and each case you need to write a new css class, name it, and apply it back to the HTML. Tailwind helps solve this by giving developers utility classes to apply to a variety of use-cases for UI design, and later opt to group reusable css into components only when it makes sense. This helps UI designs come together quicker, and it’s often easier to maintain.

#### For Module Developers:

All of Gibbon’s core css components would still be available for module developers to use: alerts, inputs, tables, etc. They’re primarily used through PHP component classes, so module developers wouldn’t be required to make many design decisions to add in their new features.

For use-cases that don’t already exist, utility classes would help developers easily fill in the gaps. They also serve as a design palette, helping ensure the module UI still matches with the overall look of the application.

#### For Theme Developers:

These days, a build process is pretty close to essential whether you’re using Bootstrap with Sass or compiling Tailwind with PostCSS. Our goal in the project is always to keep the barrier for entry low for new developers, and I believe we can achieve this with Tailwind. By splitting the core (utility) css from the theme (component) css, theme developers would have the option to either add their css on as a separate file (to make small tweaks and changes) or replace the theme css file (to make overall visual changes). 

The templating system (started in v17) would also offer theme developers the opportunity to change the structure of the theme (adjust the menu, move the sidebar, reshape the header) using just utility classes, without needing to replace the whole stylesheet.

Ideally, this means the build process would only be required for the core, and optional for theme developers. It could allow a lot of neat possibilities for theme development, which up until now has required continuously merging the core stylesheet back into the theme with each new version.

---

Overall, I feel there’s a pretty strong case for using Tailwind with Gibbon. As with any path to take, there’s up and downs in both directions, but I think it’s ultimately a direction that can benefit our project.

Some additional links:
- [5 Takeaways From Using Tailwind CSS In Real Projects | Nick Basile](https://nick-basile.com/blog/post/5-takeaways-from-using-tailwind-css-in-real-projects)
- [Going Full-Time on Tailwind CSS](https://adamwathan.me/going-full-time-on-tailwind-css/)
- [Refactoring UI](https://refactoringui.com/)

**Comment by rossdotparker** [comment]
Hi Sandra, thanks for investing so much time and thought in this proposal. To me semantic CSS makes a lot of sense, and given the way that Tailwind allowed you to rapidly build the new Gibbon website, which is fully mobile responsive, I'm inclined to think that Tailwind is an interesting route to look into.

I what some of our other dev friends, who are definitely more contemporary in their approaches than I am, might add to this conversation?

Thanks, as always, for your brilliant work in pushing out community and our platform forwards!

Ross

**Comment by leofreitas** [comment]
Hi Sandra, excellent work! I have been working with Bootstrap and Foundation, but now I'm curious for experience the Tailwind.
It seems very interesting. I'm read about it.

**Comment by yookoala** [comment]
I've been working with Bootstrap for so long that I really got used to the routine. So I'm a bit skeptical in this. But I'm willing to try and learn.

**Comment by SKuipers** [comment]
Thanks for the feedback! I think that's a fair response, and I realize Tailwind is the lesser-known of the available options 😄 Bootstrap is a great framework, I think of it like a Swiss Army knife: it's familiar and multi-purpose, developers keep it in their back-pocket and reach for it to solve a variety of UI tasks. In considering Tailwind, it has a lot of similarities, and yet it's a bit different shape of tool that seems well suited to our specific tasks. I think we could certainly aim to use many of the naming conventions established by Bootstrap (for buttons, alerts, etc), which are well-known and battle-tested.
