### ISSUE TITLE
browseBGImage field is limited to 6 chars

### ISSUE THREAD

**Issue by radelphe** [GibbonEdu/core#958]
**Description**

browseBGImage field in **Manage Library Settings** is limited to 6 chars. 

**To Reproduce**

1. Go to 'Home > School Admin > Manage Library Settings'.
2. Enter text in 'Browse Library BG Image' field.

Problem: Maxlength is 6 chars.

**Expected behavior**

According to its description, that field is to enter "URL to background image used behind library browsing screen." So I expect it should allow user to enter more than 6 chars.

**Your System**

 - Gibbon version: v18.0.01

**Comment by rossdotparker** [comment]
Hi radelphe, thanks for reporting this issue to us. Using your very detailed instructions, I've recreated the issue, and resolved it. You can see the fix in the commit below:

https://github.com/GibbonEdu/core/commit/d60431ab9aeede2d1a428efbb3ba421a08c847cb

This is in out v19.0.00 branch, but you can replicate the change in your v18.0.01 stall, and the issue should be sorted. It is a rather simple fix!
