### ISSUE TITLE
gibbonFinanceInvoice.gibbonPaymentID is not updated after payment

### ISSUE THREAD

**Issue by radelphe** [GibbonEdu/core#961]
**Describe the bug**

gibbonFinanceInvoice.gibbonPaymentID is not updated after payment

**To Reproduce**

1. In Finance, create and issue a new invoice.
2. Edit Invoice and make payment.
3. Run the following query (change %ID% to the ID of teh invoice created at step 1):

"SELECT * FROM gibbonFinanceInvoice WHERE gibbonFinanceInvoiceID = _%ID%_" 

**Problem:** gibbonFinanceInvoice.gibbonPaymentID is NULL

**Expected behavior**

gibbonFinanceInvoice.gibbonPaymentID should be set to gibbonPayment.gibbonPaymentID of the payment done at step 2.

I wonder if we can enforce that if gibbonFinanceInvoice.Status is set to "Paid" or "Paid - Partial" then gibbonFinanceInvoice.gibbonPaymentID cannot be NULL.

**Your System**

 - Gibbon version: v18.0.01

**Comment by SKuipers** [comment]
Hi @radelphe 

I've looked at the code and it appears gibbonFinanceInvoice.gibbonPaymentID may be a deprecated field. I suspect at some point in the past an invoice may have been attached to a single payment, however this is no longer the case, as there can be multiple payments per invoice. 

To retrieve these in your SQL query, be sure to look at the `foreignTable` and `foreignTableID` fields in the gibbonPayment table, which will reference back to the `gibbonFinanceInvoice` table and `gibbonFinanceInvoiceID` value.

**Comment by radelphe** [comment]
Ah! Got it. Thanks @SKuipers .
