### ISSUE TITLE
Dropdown list for bulk processing invoices does not refresh after changing view filter

### ISSUE THREAD

**Issue by radelphe** [GibbonEdu/core#962]
**Describe the bug**

Dropdown list for bulk processing invoices does not refresh after changing view filter.

**To Reproduce**

1. In Finance module, create and Issue one or multiple invoices so that they will have "Issued" Status.
2. Create new invoices with Pending status.
3. Go to Manage Invoices and note what is the filter view (e.g. Pending). If you select the item, the action menu items for bulk processing are correct for that status (e.g. here are the actions available for Pending invoices: Delete, Issue, Issue (Without Email), Export).
4. Filter the view by a different status (e.g. Issued).
5. Select an item from the list and open the dropdown list for bulk processing.

**Problem:** The items listed in the dropdown list are not refreshed. They are still for the previous status (e.g. Pending).

**Expected behavior**

Changing the filtering view should update the dropdown list for bulk processing. 

**Your System**

 - Gibbon version: v18.0.01

**Comment by SKuipers** [comment]
Hi @radelphe 

Thanks for the heads up, I was able to reproduce this issue. I've labelled it as a bug and will see if we can fix it for v19.

**Comment by SKuipers** [comment]
Hi @radelphe, I've fixed this bug for v19 in the following commit: https://github.com/GibbonEdu/core/commit/1c8dee05fe54f82cb054e1dc74d802a735384834  You can apply the same changes to v18 and should see that the dropdowns are now updating correctly based on the table filters. Thanks!
