### ISSUE TITLE
Maldivian Language (Dhivehi) not available as users language

### ISSUE THREAD

**Issue by ahmdhssn** [GibbonEdu/core#968]
We do not have Maldivian Language (Dhivehi) available for users first, second or third language.

**Comment by rossdotparker** [comment]
Hello @ahmdhssn this was true...but I've just added it : ) You can see the change in the commit below, which is in our v19.0.00 branch

https://github.com/GibbonEdu/core/commit/3304479043c2b2d3257d44c4c02d881bb5881d6b

Version 19 is due out on January 20th. If you want to access it earlier than that on v18, you can run the new SQL statement on your database now, and then remove the duplicate entry after upgrading to 18. 

Thanks!

Ross

**Comment by ahmdhssn** [comment]
Thanks @rossdotparker
Maldivian language name is Dhivehi. Maldivian will do fine too.
