### ISSUE TITLE
Cannot edit or delete first added Fee Category

### ISSUE THREAD

**Issue by ahmdhssn** [GibbonEdu/core#969]
Its not available when adding or editing fees in manage fees
but available when i choose Ad Hoc as fee from the dropdown.

**Comment by rossdotparker** [comment]
Hi @ahmdhssn this is actually a feature designed to make sure that there is always one fee category in the system. This category "Other" is useful for catching fees that might not fit anywhere else. You could remove it direct from the database, but this might cause unexpected knock on effects...so be careful! Ross.

**Comment by ahmdhssn** [comment]
Hi @rossdotparker,
Please have a look at the screenshots below. "Monthly School Fees"
![image](https://user-images.githubusercontent.com/57095269/70387131-074c9d00-19c3-11ea-91fe-cc0a4dab783e.png)
![image](https://user-images.githubusercontent.com/57095269/70387139-19c6d680-19c3-11ea-817d-84c240c7073e.png)
![image](https://user-images.githubusercontent.com/57095269/70387171-89d55c80-19c3-11ea-96ed-40e3c96e1c07.png)
Thanks
Ahmed

**Comment by rossdotparker** [comment]
Hi Ahmed, that is very odd. I am guessing the gibbonFinanceFeeID value for Monthly School Fees is 000001. Is that correct? When you installed the system, was there a value for Other? Thanks!

Hi @SKuipers I think this might be a bug. Are you able to test a fresh install, and see if the default Other value it exists? If not, I wonder where along the line it went missing?

**Comment by SKuipers** [comment]
Looks like the code to add the Other fee category exists in the demo data but not the base install. I've updated the .sql files in [this commit](https://github.com/GibbonEdu/core/commit/af94ff24cbd39249676797aa2739a9054e402ac6) to correct the issue, but I believe we'll need to make a note when re-generating sql files to keep the Other category in gibbon.sql 🤔 

Ahmed, if you run the following SQL on your server, it will remove the Monthly School Fees category and replace it with the intended Other category.

```
DELETE FROM `gibbonFinanceFeeCategory` WHERE `gibbonFinanceFeeCategoryID`=0001;
INSERT INTO `gibbonFinanceFeeCategory` (`gibbonFinanceFeeCategoryID`, `name`, `nameShort`, `description`, `active`, `gibbonPersonIDCreator`, `timestampCreator`, `gibbonPersonIDUpdate`, `timestampUpdate`)
VALUES (0001,'Other','OTHR','Category for fees not fitting into any other category.','Y',0000000001,'2013-07-12 08:25:32',NULL,NULL);
```

**Comment by ahmdhssn** [comment]
Its was the same bug as mentioned above. SQL worked fine. 
Thank you @rossdotparker and @SKuipers.  That was quick. 
Thank you @rossdotparker and @SKuipers.
