### ISSUE TITLE
Finance Fees cannot be deleted

### ISSUE THREAD

**Issue by ahmdhssn** [GibbonEdu/core#974]
Hi,
I think its a bug. Finance user must be either able to delete unused fees or at-least disable them. 
![image](https://user-images.githubusercontent.com/57095269/70898812-37291f80-2017-11ea-8b8b-8361255b4fd2.png)
Thanks
Ahmed

**Comment by SKuipers** [comment]
Hi Ahmed,

I believe the system is designed to prevent deleting fees to ensure there's no loss of important data. However, you can disable them by clicking the pencil and setting Active to No. Hope this helps!

<img width="788" alt="Screen Shot 2019-12-17 at 9 10 43 AM" src="https://user-images.githubusercontent.com/897700/70955912-57a3b900-20ad-11ea-8fcd-9880e98fa98c.png">

**Comment by ahmdhssn** [comment]
Thanks @SKuipers. Somehow i didn't see it. 
Looks like after making inactive, still appears in the dropdown adding invoices.

**Comment by SKuipers** [comment]
Well caught! They shouldn't still be showing up in the list, that part is a bug. I've fixed it here for v19: https://github.com/GibbonEdu/core/commit/4eaebf435be2d8c1dda31738091aba3d43908c8b
