### ISSUE TITLE
DateStart imported incorrectly

### ISSUE THREAD

**Issue by ahmdhssn** [GibbonEdu/core#980]
Hi,
Im trying to import the student admission dates to the dateStart field in gibbonPerson. 
It seems like the importer is using a different date format. Some dates are imported incorrectly as "1970-01-01"
I have a dateStart column in the import file formatted as "dd/mm/yyyy"

**Comment by SKuipers** [comment]
Hi @ahmdhssn 

The importer in Gibbon uses the PHP `strtotime()` function to convert strings to dates. This function looks at the separators and converts the dates based on the characters used, however the use of / slashes in PHP dates is unfortunately american-centric. [See the docs for more info](https://www.php.net/manual/en/function.strtotime#refsect1-function.strtotime-notes). 

One way to overcome this is to use a spreadsheet formula to convert your dates to YYYY-MM-DD before uploading, or to use . dots as separators.

You can find a note about dates in the importer, and a link to the docs for reference: 
<img width="805" alt="Screen Shot 2020-01-06 at 1 01 14 PM" src="https://user-images.githubusercontent.com/897700/71796271-dffdf400-3084-11ea-8a83-cae8cfdf0a43.png">
