### ISSUE TITLE
Text display bug on add lesson plan page

### ISSUE THREAD

**Issue by fvlasie** [GibbonEdu/core#982]
```
.../c/index.php?q=/modules/Planner/planner_add.php&viewBy=class&gibbonCourseClassID=00000141&subView=
```
<img width="783" alt="Screen Shot 2020-01-12 at 11 25 16 PM" src="https://user-images.githubusercontent.com/33334298/72238686-58881780-3593-11ea-84f5-f89bec473854.png">

**Comment by fvlasie** [comment]
"CMIIse" is not a string that appears in the codebase, so I could not track it down.

**Comment by SKuipers** [comment]
Hi FV,

Any chance you have a string replacement setup in your system? Looks like the letters "hoo" are being replace with "MII". Otherwise, perhaps some kind of multi-byte string issue 🤔

**Comment by fvlasie** [comment]
Hello Sandra, 
I have no string replacements set. It is strange...

**Comment by SKuipers** [comment]
Hi FV. I'm a bit stumped on this one, I wasn't able to reproduce it 🤔 Do you want to keep an eye and see if it crops up anywhere else, or if you have a development install, test it out there? Thanks!
